-- Anarlog — every call this API accepts, as data.
--
-- GENERATED from https://api.anarlog.so/openapi.json
-- Published on the vendor's own documentation site (https://api.anarlog.so).
-- 110 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "anarlog-mcp",
  name = "Anarlog",
  base = "https://api.anarlog.so/mcp",
  docs = "https://nango.dev/docs/api-integrations/anarlog-mcp",
  auth = {
    kind = "manual",
    header = "authorization",
    format = "Bearer {token}",
    env = "ANARLOG_MCP_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["anarlog-mcp.can_start_trial"] = { method = "GET", url = "https://api.anarlog.so/mcp/subscription/can-start-trial" },
    ["anarlog-mcp.cancel_attachment_backup_deletion"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/attachment-backups/delete/cancel", body = {"attachmentRef", "deleteRequestId", "objectKey", "versionRef"} },
    ["anarlog-mcp.claim_e2ee_identity"] = { method = "PUT", url = "https://api.anarlog.so/mcp/sync/e2ee/identity", body = {"keyId"} },
    ["anarlog-mcp.claim_shared_note_handoff"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/handoffs/claim", body = {"leaseId", "requestId"} },
    ["anarlog-mcp.consume_e2ee_device_enrollment"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/e2ee/device-enrollments/{request_id}/consume", path = {"request_id"}, header = {"x-device-fingerprint"}, body = {"publicKey"} },
    ["anarlog-mcp.create_credentials"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/token", header = {"x-anarlog-e2ee-key-id", "x-anarlog-e2ee-member-public-key", "x-anarlog-cloudsync-transports"} },
    ["anarlog-mcp.create_key"] = { method = "POST", url = "https://api.anarlog.so/mcp/v1/cloud-api/keys", body = {"name"} },
    ["anarlog-mcp.create_link_shared_note_handoff"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/link/{share_id}/handoff", path = {"share_id"} },
    ["anarlog-mcp.create_live_ticket"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/shares/{share_id}/live/ticket", path = {"share_id"} },
    ["anarlog-mcp.create_public_shared_note_handoff"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/public/{slug}/handoff", path = {"slug"} },
    ["anarlog-mcp.create_replica_credentials"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/replica/credentials", header = {"x-anarlog-e2ee-key-id", "x-anarlog-e2ee-member-public-key"} },
    ["anarlog-mcp.create_session"] = { method = "POST", url = "https://api.anarlog.so/mcp/nango/session", body = {"connection_id", "integration_id", "mode"} },
    ["anarlog-mcp.create_stable_shared_note_handoff"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/share/{share_id}/handoff", path = {"share_id"} },
    ["anarlog-mcp.crm_search_contacts"] = { method = "POST", url = "https://api.anarlog.so/mcp/crm/search-contacts", body = {"connection_id", "email", "limit", "name", "provider"} },
    ["anarlog-mcp.delete_account"] = { method = "DELETE", url = "https://api.anarlog.so/mcp/subscription/delete-account" },
    ["anarlog-mcp.delete_attachment_backup"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/attachment-backups/delete", body = {"attachmentRef", "deleteRequestId", "objectKey", "versionRef"} },
    ["anarlog-mcp.delete_connection"] = { method = "DELETE", url = "https://api.anarlog.so/mcp/nango/connections", body = {"connection_id", "integration_id"} },
    ["anarlog-mcp.delete_device"] = { method = "DELETE", url = "https://api.anarlog.so/mcp/sync/devices/{fingerprint}", path = {"fingerprint"} },
    ["anarlog-mcp.delete_snapshot"] = { method = "DELETE", url = "https://api.anarlog.so/mcp/v1/sync-snapshots/{session_id}", path = {"session_id"} },
    ["anarlog-mcp.diarize"] = { method = "POST", url = "https://api.anarlog.so/mcp/pyannote/v1/diarize", body = {"confidence", "exclusive", "maxSpeakers", "minSpeakers", "model", "numSpeakers", "transcription", "transcriptionConfig", "turnLevelConfidence", "url"} },
    ["anarlog-mcp.download_access_shared_attachment"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/access/{share_id}/attachments/{attachment_id}/download", path = {"share_id", "attachment_id"} },
    ["anarlog-mcp.download_attachment_backup"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/attachment-backups/download", body = {"objectKey"} },
    ["anarlog-mcp.download_handoff_shared_attachment"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/handoffs/attachments/{attachment_id}/download", path = {"attachment_id"}, body = {"leaseId"} },
    ["anarlog-mcp.download_link_shared_attachment"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/link/{share_id}/attachments/{attachment_id}/download", path = {"share_id", "attachment_id"} },
    ["anarlog-mcp.download_public_shared_attachment"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/public/{slug}/attachments/{attachment_id}/download", path = {"slug", "attachment_id"} },
    ["anarlog-mcp.download_stable_shared_attachment"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/share/{share_id}/attachments/{attachment_id}/download", path = {"share_id", "attachment_id"} },
    ["anarlog-mcp.edit_session_share_snapshot"] = { method = "PUT", url = "https://api.anarlog.so/mcp/sync/shares/{share_id}/web-edit", path = {"share_id"} },
    ["anarlog-mcp.export_meeting"] = { method = "GET", url = "https://api.anarlog.so/mcp/v1/meetings/{meeting_id}/export", path = {"meeting_id"}, query = {"format"} },
    ["anarlog-mcp.fathom_import_meetings"] = { method = "POST", url = "https://api.anarlog.so/mcp/fathom/import-meetings", body = {"connection_id", "known_meeting_ids"} },
    ["anarlog-mcp.finalize_attachment_backup"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/attachment-backups/finalize", body = {"objectKey"} },
    ["anarlog-mcp.finalize_shared_attachment"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/shares/{share_id}/attachments/finalize", path = {"share_id"}, body = {"objectKey"} },
    ["anarlog-mcp.get_devices"] = { method = "GET", url = "https://api.anarlog.so/mcp/sync/devices" },
    ["anarlog-mcp.get_history"] = { method = "GET", url = "https://api.anarlog.so/mcp/v1/meetings/{meeting_id}/history", path = {"meeting_id"}, query = {"limit", "offset"} },
    ["anarlog-mcp.get_job_by_id"] = { method = "GET", url = "https://api.anarlog.so/mcp/pyannote/v1/jobs/{jobId}", path = {"jobId"} },
    ["anarlog-mcp.get_media_upload_url"] = { method = "POST", url = "https://api.anarlog.so/mcp/pyannote/v1/media/input", body = {"url"} },
    ["anarlog-mcp.get_meeting"] = { method = "GET", url = "https://api.anarlog.so/mcp/v1/meetings/{meeting_id}", path = {"meeting_id"} },
    ["anarlog-mcp.get_settings"] = { method = "GET", url = "https://api.anarlog.so/mcp/v1/cloud-api/settings" },
    ["anarlog-mcp.get_transcript"] = { method = "GET", url = "https://api.anarlog.so/mcp/v1/meetings/{meeting_id}/transcript", path = {"meeting_id"}, query = {"offset", "limit"} },
    ["anarlog-mcp.get_workspace_e2ee_key_recipients"] = { method = "GET", url = "https://api.anarlog.so/mcp/sync/e2ee/workspaces/{workspace_id}/recipients", path = {"workspace_id"} },
    ["anarlog-mcp.github_list_repos"] = { method = "POST", url = "https://api.anarlog.so/mcp/ticket/github/list-repos", body = {"connection_id", "cursor", "limit"} },
    ["anarlog-mcp.github_list_tickets"] = { method = "POST", url = "https://api.anarlog.so/mcp/ticket/github/list-tickets", body = {"connection_id", "cursor", "labels", "limit", "owner", "repo", "state"} },
    ["anarlog-mcp.google_drive_export_markdown"] = { method = "POST", url = "https://api.anarlog.so/mcp/nango/google-drive/export", body = {"connection_id", "file_id", "filename", "folder_id", "format", "markdown", "meeting_id"} },
    ["anarlog-mcp.google_drive_picker_complete"] = { method = "POST", url = "https://api.anarlog.so/mcp/nango/google-drive/picker-complete", body = {"code", "folder_id", "state"} },
    ["anarlog-mcp.google_drive_picker_start"] = { method = "POST", url = "https://api.anarlog.so/mcp/nango/google-drive/picker-start", body = {"connection_id"} },
    ["anarlog-mcp.google_drive_prepare_export"] = { method = "POST", url = "https://api.anarlog.so/mcp/nango/google-drive/prepare-export", body = {"connection_id", "folder_id", "format", "meeting_id"} },
    ["anarlog-mcp.google_drive_validate_folder"] = { method = "POST", url = "https://api.anarlog.so/mcp/nango/google-drive/folder", body = {"connection_id", "folder_id"} },
    ["anarlog-mcp.google_get_attachment"] = { method = "POST", url = "https://api.anarlog.so/mcp/mail/google/get-attachment", body = {"attachment_id", "connection_id", "message_id"} },
    ["anarlog-mcp.google_get_message"] = { method = "POST", url = "https://api.anarlog.so/mcp/mail/google/get-message", body = {"connection_id", "format", "id", "metadata_headers"} },
    ["anarlog-mcp.google_get_profile"] = { method = "POST", url = "https://api.anarlog.so/mcp/mail/google/get-profile", body = {"connection_id"} },
    ["anarlog-mcp.google_get_thread"] = { method = "POST", url = "https://api.anarlog.so/mcp/mail/google/get-thread", body = {"connection_id", "format", "id", "metadata_headers"} },
    ["anarlog-mcp.google_list_calendars"] = { method = "POST", url = "https://api.anarlog.so/mcp/calendar/google/list-calendars", body = {"connection_id"} },
    ["anarlog-mcp.google_list_events"] = { method = "POST", url = "https://api.anarlog.so/mcp/calendar/google/list-events", body = {"calendar_id", "connection_id", "max_results", "order_by", "page_token", "single_events", "time_max", "time_min"} },
    ["anarlog-mcp.google_list_history"] = { method = "POST", url = "https://api.anarlog.so/mcp/mail/google/list-history", body = {"connection_id", "history_types", "label_id", "max_results", "page_token", "start_history_id"} },
    ["anarlog-mcp.google_list_labels"] = { method = "POST", url = "https://api.anarlog.so/mcp/mail/google/list-labels", body = {"connection_id"} },
    ["anarlog-mcp.google_list_messages"] = { method = "POST", url = "https://api.anarlog.so/mcp/mail/google/list-messages", body = {"connection_id", "include_spam_trash", "label_ids", "max_results", "page_token", "q"} },
    ["anarlog-mcp.google_list_threads"] = { method = "POST", url = "https://api.anarlog.so/mcp/mail/google/list-threads", body = {"connection_id", "include_spam_trash", "label_ids", "max_results", "page_token", "q"} },
    ["anarlog-mcp.google_meet_import_meetings"] = { method = "POST", url = "https://api.anarlog.so/mcp/google-meet/import-meetings", body = {"connection_id", "known_meeting_ids"} },
    ["anarlog-mcp.grant_attachment_backup_upload"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/attachment-backups/upload-grant", body = {"ciphertextSha256", "objectKey"} },
    ["anarlog-mcp.grant_shared_attachment_upload"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/shares/{share_id}/attachments/upload-grant", path = {"share_id"}, body = {"objectKey", "sha256"} },
    ["anarlog-mcp.heartbeat_meeting_device"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/meetings/{meeting_key}/devices", path = {"meeting_key"}, header = {"x-device-fingerprint"}, body = {"intent"} },
    ["anarlog-mcp.identify"] = { method = "POST", url = "https://api.anarlog.so/mcp/pyannote/v1/identify", body = {"confidence", "exclusive", "matching", "maxSpeakers", "minSpeakers", "model", "numSpeakers", "turnLevelConfidence", "url", "voiceprints"} },
    ["anarlog-mcp.linear_create_issue"] = { method = "POST", url = "https://api.anarlog.so/mcp/ticket/linear/create-issue", body = {"connection_id", "description", "team_id", "title"} },
    ["anarlog-mcp.linear_list_teams"] = { method = "POST", url = "https://api.anarlog.so/mcp/ticket/linear/list-teams", body = {"connection_id", "cursor", "limit"} },
    ["anarlog-mcp.linear_list_tickets"] = { method = "POST", url = "https://api.anarlog.so/mcp/ticket/linear/list-tickets", body = {"connection_id", "cursor", "limit", "query", "team_id"} },
    ["anarlog-mcp.list_connections"] = { method = "GET", url = "https://api.anarlog.so/mcp/nango/connections" },
    ["anarlog-mcp.list_keys"] = { method = "GET", url = "https://api.anarlog.so/mcp/v1/cloud-api/keys" },
    ["anarlog-mcp.list_meetings"] = { method = "GET", url = "https://api.anarlog.so/mcp/v1/meetings", query = {"query", "series_id", "limit", "offset"} },
    ["anarlog-mcp.list_slack_channels"] = { method = "GET", url = "https://api.anarlog.so/mcp/messenger/slack/channels" },
    ["anarlog-mcp.llm_chat_completions"] = { method = "POST", url = "https://api.anarlog.so/mcp/llm/chat/completions", header = {"x-char-task"} },
    ["anarlog-mcp.microsoft_teams_import_meetings"] = { method = "POST", url = "https://api.anarlog.so/mcp/microsoft-teams/import-meetings", body = {"connection_id", "known_meeting_ids"} },
    ["anarlog-mcp.nango_webhook"] = { method = "POST", url = "https://api.anarlog.so/mcp/nango/webhook" },
    ["anarlog-mcp.notion_append_update"] = { method = "POST", url = "https://api.anarlog.so/mcp/notion/append-update", body = {"connection_id", "heading", "markdown", "page_id"} },
    ["anarlog-mcp.notion_import_meetings"] = { method = "POST", url = "https://api.anarlog.so/mcp/notion/import-meetings", body = {"connection_id", "known_meeting_ids"} },
    ["anarlog-mcp.notion_search_pages"] = { method = "POST", url = "https://api.anarlog.so/mcp/notion/search-pages", body = {"connection_id", "query"} },
    ["anarlog-mcp.outlook_list_calendars"] = { method = "POST", url = "https://api.anarlog.so/mcp/calendar/outlook/list-calendars", body = {"connection_id"} },
    ["anarlog-mcp.outlook_list_events"] = { method = "POST", url = "https://api.anarlog.so/mcp/calendar/outlook/list-events", body = {"calendar_id", "connection_id", "max_results", "order_by", "time_max", "time_min"} },
    ["anarlog-mcp.patch_device"] = { method = "PATCH", url = "https://api.anarlog.so/mcp/sync/devices/{fingerprint}", path = {"fingerprint"}, body = {"deviceName"} },
    ["anarlog-mcp.promote_attachment_backup"] = { method = "PUT", url = "https://api.anarlog.so/mcp/sync/attachment-backups/head", body = {"expectedCurrentObjectKey", "objectKey"} },
    ["anarlog-mcp.publish_e2ee_witness"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/e2ee/witness/{workspace_id}", path = {"workspace_id"}, body = {"events", "initialize"} },
    ["anarlog-mcp.publish_session_share_snapshot"] = { method = "PUT", url = "https://api.anarlog.so/mcp/sync/shares/{share_id}/snapshot", path = {"share_id"} },
    ["anarlog-mcp.publish_snapshot"] = { method = "PUT", url = "https://api.anarlog.so/mcp/v1/sync-snapshots/{session_id}", path = {"session_id"}, body = {"action_items", "created_at", "ended_at", "folder_path", "id", "kind", "language", "note", "participants", "series_id", "started_at", "status", "summaries", "timezone", "title", "updated_at"} },
    ["anarlog-mcp.read_current_attachment_backup"] = { method = "GET", url = "https://api.anarlog.so/mcp/sync/attachment-backups/head/{attachment_ref}", path = {"attachment_ref"} },
    ["anarlog-mcp.read_e2ee_witness"] = { method = "GET", url = "https://api.anarlog.so/mcp/sync/e2ee/witness/{workspace_id}", path = {"workspace_id"}, query = {"afterSequence", "throughSequence"} },
    ["anarlog-mcp.read_link_shared_note"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/link/{share_id}", path = {"share_id"} },
    ["anarlog-mcp.read_link_shared_note_preview"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/link/{share_id}/preview", path = {"share_id"}, body = {"previewToken"} },
    ["anarlog-mcp.read_public_shared_note"] = { method = "GET", url = "https://api.anarlog.so/mcp/shared-notes/public/{slug}", path = {"slug"} },
    ["anarlog-mcp.read_public_shared_note_preview"] = { method = "GET", url = "https://api.anarlog.so/mcp/shared-notes/public/{slug}/preview", path = {"slug"} },
    ["anarlog-mcp.read_short_link_shared_note_preview"] = { method = "GET", url = "https://api.anarlog.so/mcp/shared-notes/links/{link_id}/preview", path = {"link_id"} },
    ["anarlog-mcp.read_stable_shared_note"] = { method = "GET", url = "https://api.anarlog.so/mcp/shared-notes/share/{share_id}", path = {"share_id"} },
    ["anarlog-mcp.read_stable_shared_note_preview"] = { method = "GET", url = "https://api.anarlog.so/mcp/shared-notes/share/{share_id}/preview", path = {"share_id"} },
    ["anarlog-mcp.register_e2ee_device_enrollment"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/e2ee/device-enrollments", header = {"x-device-fingerprint", "x-anarlog-device-name"}, body = {"publicKey", "replaceFingerprint"} },
    ["anarlog-mcp.reserve_attachment_backup"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/attachment-backups/reserve", body = {"attachmentRef", "ciphertextSizeBytes", "formatVersion", "versionRef"} },
    ["anarlog-mcp.reserve_shared_attachment"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/shares/{share_id}/attachments/reserve", path = {"share_id"}, body = {"attachmentRef", "contentType", "filename", "sizeBytes", "versionRef"} },
    ["anarlog-mcp.revoke_key"] = { method = "DELETE", url = "https://api.anarlog.so/mcp/v1/cloud-api/keys/{key_id}", path = {"key_id"} },
    ["anarlog-mcp.seal_e2ee_device_enrollment"] = { method = "POST", url = "https://api.anarlog.so/mcp/sync/e2ee/device-enrollments/{request_id}/seal", path = {"request_id"}, body = {"ciphertext", "ephemeralPublicKey", "nonce"} },
    ["anarlog-mcp.send_shared_note_invitation_email"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/invitations/{invitation_id}/email", path = {"invitation_id"}, body = {"fromName", "inviteToken", "noteTitle", "shareId"} },
    ["anarlog-mcp.send_shared_note_recap_email"] = { method = "POST", url = "https://api.anarlog.so/mcp/shared-notes/{share_id}/recap/email", path = {"share_id"}, body = {"deliveryId", "noteBody", "noteTitle", "recipients", "senderName"} },
    ["anarlog-mcp.send_slack_message"] = { method = "POST", url = "https://api.anarlog.so/mcp/messenger/slack/messages", body = {"channel", "text"} },
    ["anarlog-mcp.send_workspace_invitation_email"] = { method = "POST", url = "https://api.anarlog.so/mcp/workspaces/invitations/{invitation_id}/email", path = {"invitation_id"}, body = {"fromName", "inviteToken", "workspaceId", "workspaceName"} },
    ["anarlog-mcp.set_workspace_e2ee_key"] = { method = "PUT", url = "https://api.anarlog.so/mcp/sync/e2ee/workspaces/{workspace_id}/key", path = {"workspace_id"}, body = {"grants", "keyId"} },
    ["anarlog-mcp.start_trial"] = { method = "POST", url = "https://api.anarlog.so/mcp/subscription/start-trial", query = {"interval"} },
    ["anarlog-mcp.stt_listen_batch"] = { method = "POST", url = "https://api.anarlog.so/mcp/stt/listen", query = {"provider", "model", "language", "keywords", "num_speakers", "min_speakers", "max_speakers", "sample_rate", "channels", "callback"}, body = {"url"} },
    ["anarlog-mcp.stt_listen_stream"] = { method = "GET", url = "https://api.anarlog.so/mcp/stt/listen", query = {"provider", "model", "language", "keywords", "num_speakers", "min_speakers", "max_speakers", "sample_rate", "channels", "encoding"} },
    ["anarlog-mcp.stt_status"] = { method = "GET", url = "https://api.anarlog.so/mcp/stt/status/{pipeline_id}", path = {"pipeline_id"} },
    ["anarlog-mcp.update_settings"] = { method = "PUT", url = "https://api.anarlog.so/mcp/v1/cloud-api/settings", body = {"enabled"} },
    ["anarlog-mcp.voiceprint"] = { method = "POST", url = "https://api.anarlog.so/mcp/pyannote/v1/voiceprint", body = {"model", "url"} },
    ["anarlog-mcp.wait_e2ee_witness"] = { method = "GET", url = "https://api.anarlog.so/mcp/sync/e2ee/witness/{workspace_id}/wait", path = {"workspace_id"}, query = {"afterSequence"} },
    ["anarlog-mcp.webex_import_meetings"] = { method = "POST", url = "https://api.anarlog.so/mcp/webex/import-meetings", body = {"connection_id", "known_meeting_ids"} },
    ["anarlog-mcp.whoami"] = { method = "GET", url = "https://api.anarlog.so/mcp/nango/whoami" },
    ["anarlog-mcp.zoom_import_meetings"] = { method = "POST", url = "https://api.anarlog.so/mcp/zoom/import-meetings", body = {"connection_id", "known_meeting_ids"} },
  },
}
