-- Slack — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/slack.com/1.7.0/openapi.json
-- APIs.guru's mirror of slack.com, matched on slack.com. A mirror lags the vendor.
-- 174 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "slack-app-configuration",
  name = "Slack",
  base = "https://slack.com/api",
  docs = "https://nango.dev/docs/api-integrations/slack-app-configuration",
  auth = {
    kind = "manual",
    header = "authorization",
    format = "Bearer {token}",
    env = "SLACK_APP_CONFIGURATION_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["slack-app-configuration.admin_apps_approve"] = { method = "POST", url = "https://slack.com/api/admin.apps.approve", body = {"app_id", "request_id", "team_id"} },
    ["slack-app-configuration.admin_apps_approved_list"] = { method = "GET", url = "https://slack.com/api/admin.apps.approved.list", query = {"limit", "cursor", "team_id", "enterprise_id"} },
    ["slack-app-configuration.admin_apps_requests_list"] = { method = "GET", url = "https://slack.com/api/admin.apps.requests.list", query = {"limit", "cursor", "team_id"} },
    ["slack-app-configuration.admin_apps_restrict"] = { method = "POST", url = "https://slack.com/api/admin.apps.restrict", body = {"app_id", "request_id", "team_id"} },
    ["slack-app-configuration.admin_apps_restricted_list"] = { method = "GET", url = "https://slack.com/api/admin.apps.restricted.list", query = {"limit", "cursor", "team_id", "enterprise_id"} },
    ["slack-app-configuration.admin_conversations_archive"] = { method = "POST", url = "https://slack.com/api/admin.conversations.archive", body = {"channel_id"} },
    ["slack-app-configuration.admin_conversations_convert_to_private"] = { method = "POST", url = "https://slack.com/api/admin.conversations.convertToPrivate", body = {"channel_id"} },
    ["slack-app-configuration.admin_conversations_create"] = { method = "POST", url = "https://slack.com/api/admin.conversations.create", body = {"description", "is_private", "name", "org_wide", "team_id"} },
    ["slack-app-configuration.admin_conversations_delete"] = { method = "POST", url = "https://slack.com/api/admin.conversations.delete", body = {"channel_id"} },
    ["slack-app-configuration.admin_conversations_disconnect_shared"] = { method = "POST", url = "https://slack.com/api/admin.conversations.disconnectShared", body = {"channel_id", "leaving_team_ids"} },
    ["slack-app-configuration.admin_conversations_ekm_list_original_connected_channel_info"] = { method = "GET", url = "https://slack.com/api/admin.conversations.ekm.listOriginalConnectedChannelInfo", query = {"channel_ids", "team_ids", "limit", "cursor"} },
    ["slack-app-configuration.admin_conversations_get_conversation_prefs"] = { method = "GET", url = "https://slack.com/api/admin.conversations.getConversationPrefs", query = {"channel_id"} },
    ["slack-app-configuration.admin_conversations_get_teams"] = { method = "GET", url = "https://slack.com/api/admin.conversations.getTeams", query = {"channel_id", "cursor", "limit"} },
    ["slack-app-configuration.admin_conversations_invite"] = { method = "POST", url = "https://slack.com/api/admin.conversations.invite", body = {"channel_id", "user_ids"} },
    ["slack-app-configuration.admin_conversations_rename"] = { method = "POST", url = "https://slack.com/api/admin.conversations.rename", body = {"channel_id", "name"} },
    ["slack-app-configuration.admin_conversations_restrict_access_add_group"] = { method = "POST", url = "https://slack.com/api/admin.conversations.restrictAccess.addGroup", body = {"channel_id", "group_id", "team_id"} },
    ["slack-app-configuration.admin_conversations_restrict_access_list_groups"] = { method = "GET", url = "https://slack.com/api/admin.conversations.restrictAccess.listGroups", query = {"channel_id", "team_id"} },
    ["slack-app-configuration.admin_conversations_restrict_access_remove_group"] = { method = "POST", url = "https://slack.com/api/admin.conversations.restrictAccess.removeGroup", body = {"channel_id", "group_id", "team_id"} },
    ["slack-app-configuration.admin_conversations_search"] = { method = "GET", url = "https://slack.com/api/admin.conversations.search", query = {"team_ids", "query", "limit", "cursor", "search_channel_types", "sort", "sort_dir"} },
    ["slack-app-configuration.admin_conversations_set_conversation_prefs"] = { method = "POST", url = "https://slack.com/api/admin.conversations.setConversationPrefs", body = {"channel_id", "prefs"} },
    ["slack-app-configuration.admin_conversations_set_teams"] = { method = "POST", url = "https://slack.com/api/admin.conversations.setTeams", body = {"channel_id", "org_channel", "target_team_ids", "team_id"} },
    ["slack-app-configuration.admin_conversations_unarchive"] = { method = "POST", url = "https://slack.com/api/admin.conversations.unarchive", body = {"channel_id"} },
    ["slack-app-configuration.admin_emoji_add"] = { method = "POST", url = "https://slack.com/api/admin.emoji.add", body = {"name", "url"} },
    ["slack-app-configuration.admin_emoji_add_alias"] = { method = "POST", url = "https://slack.com/api/admin.emoji.addAlias", body = {"alias_for", "name"} },
    ["slack-app-configuration.admin_emoji_list"] = { method = "GET", url = "https://slack.com/api/admin.emoji.list", query = {"cursor", "limit"} },
    ["slack-app-configuration.admin_emoji_remove"] = { method = "POST", url = "https://slack.com/api/admin.emoji.remove", body = {"name"} },
    ["slack-app-configuration.admin_emoji_rename"] = { method = "POST", url = "https://slack.com/api/admin.emoji.rename", body = {"name", "new_name"} },
    ["slack-app-configuration.admin_invite_requests_approve"] = { method = "POST", url = "https://slack.com/api/admin.inviteRequests.approve" },
    ["slack-app-configuration.admin_invite_requests_approved_list"] = { method = "GET", url = "https://slack.com/api/admin.inviteRequests.approved.list", query = {"team_id", "cursor", "limit"} },
    ["slack-app-configuration.admin_invite_requests_denied_list"] = { method = "GET", url = "https://slack.com/api/admin.inviteRequests.denied.list", query = {"team_id", "cursor", "limit"} },
    ["slack-app-configuration.admin_invite_requests_deny"] = { method = "POST", url = "https://slack.com/api/admin.inviteRequests.deny" },
    ["slack-app-configuration.admin_invite_requests_list"] = { method = "GET", url = "https://slack.com/api/admin.inviteRequests.list", query = {"team_id", "cursor", "limit"} },
    ["slack-app-configuration.admin_teams_admins_list"] = { method = "GET", url = "https://slack.com/api/admin.teams.admins.list", query = {"limit", "cursor", "team_id"} },
    ["slack-app-configuration.admin_teams_create"] = { method = "POST", url = "https://slack.com/api/admin.teams.create", body = {"team_description", "team_discoverability", "team_domain", "team_name"} },
    ["slack-app-configuration.admin_teams_list"] = { method = "GET", url = "https://slack.com/api/admin.teams.list", query = {"limit", "cursor"} },
    ["slack-app-configuration.admin_teams_owners_list"] = { method = "GET", url = "https://slack.com/api/admin.teams.owners.list", query = {"team_id", "limit", "cursor"} },
    ["slack-app-configuration.admin_teams_settings_info"] = { method = "GET", url = "https://slack.com/api/admin.teams.settings.info", query = {"team_id"} },
    ["slack-app-configuration.admin_teams_settings_set_default_channels"] = { method = "POST", url = "https://slack.com/api/admin.teams.settings.setDefaultChannels", body = {"channel_ids", "team_id"} },
    ["slack-app-configuration.admin_teams_settings_set_description"] = { method = "POST", url = "https://slack.com/api/admin.teams.settings.setDescription", body = {"description", "team_id"} },
    ["slack-app-configuration.admin_teams_settings_set_discoverability"] = { method = "POST", url = "https://slack.com/api/admin.teams.settings.setDiscoverability", body = {"discoverability", "team_id"} },
    ["slack-app-configuration.admin_teams_settings_set_icon"] = { method = "POST", url = "https://slack.com/api/admin.teams.settings.setIcon", body = {"image_url", "team_id"} },
    ["slack-app-configuration.admin_teams_settings_set_name"] = { method = "POST", url = "https://slack.com/api/admin.teams.settings.setName", body = {"name", "team_id"} },
    ["slack-app-configuration.admin_usergroups_add_channels"] = { method = "POST", url = "https://slack.com/api/admin.usergroups.addChannels", body = {"channel_ids", "team_id", "usergroup_id"} },
    ["slack-app-configuration.admin_usergroups_add_teams"] = { method = "POST", url = "https://slack.com/api/admin.usergroups.addTeams", body = {"auto_provision", "team_ids", "usergroup_id"} },
    ["slack-app-configuration.admin_usergroups_list_channels"] = { method = "GET", url = "https://slack.com/api/admin.usergroups.listChannels", query = {"usergroup_id", "team_id", "include_num_members"} },
    ["slack-app-configuration.admin_usergroups_remove_channels"] = { method = "POST", url = "https://slack.com/api/admin.usergroups.removeChannels", body = {"channel_ids", "usergroup_id"} },
    ["slack-app-configuration.admin_users_assign"] = { method = "POST", url = "https://slack.com/api/admin.users.assign", body = {"channel_ids", "is_restricted", "is_ultra_restricted", "team_id", "user_id"} },
    ["slack-app-configuration.admin_users_invite"] = { method = "POST", url = "https://slack.com/api/admin.users.invite", body = {"channel_ids", "custom_message", "email", "guest_expiration_ts", "is_restricted", "is_ultra_restricted", "real_name", "resend", "team_id"} },
    ["slack-app-configuration.admin_users_list"] = { method = "GET", url = "https://slack.com/api/admin.users.list", query = {"team_id", "cursor", "limit"} },
    ["slack-app-configuration.admin_users_remove"] = { method = "POST", url = "https://slack.com/api/admin.users.remove", body = {"team_id", "user_id"} },
    ["slack-app-configuration.admin_users_session_invalidate"] = { method = "POST", url = "https://slack.com/api/admin.users.session.invalidate", body = {"session_id", "team_id"} },
    ["slack-app-configuration.admin_users_session_reset"] = { method = "POST", url = "https://slack.com/api/admin.users.session.reset", body = {"mobile_only", "user_id", "web_only"} },
    ["slack-app-configuration.admin_users_set_admin"] = { method = "POST", url = "https://slack.com/api/admin.users.setAdmin", body = {"team_id", "user_id"} },
    ["slack-app-configuration.admin_users_set_expiration"] = { method = "POST", url = "https://slack.com/api/admin.users.setExpiration", body = {"expiration_ts", "team_id", "user_id"} },
    ["slack-app-configuration.admin_users_set_owner"] = { method = "POST", url = "https://slack.com/api/admin.users.setOwner", body = {"team_id", "user_id"} },
    ["slack-app-configuration.admin_users_set_regular"] = { method = "POST", url = "https://slack.com/api/admin.users.setRegular", body = {"team_id", "user_id"} },
    ["slack-app-configuration.api_test"] = { method = "GET", url = "https://slack.com/api/api.test", query = {"error", "foo"} },
    ["slack-app-configuration.apps_event_authorizations_list"] = { method = "GET", url = "https://slack.com/api/apps.event.authorizations.list", query = {"event_context", "cursor", "limit"} },
    ["slack-app-configuration.apps_permissions_info"] = { method = "GET", url = "https://slack.com/api/apps.permissions.info" },
    ["slack-app-configuration.apps_permissions_request"] = { method = "GET", url = "https://slack.com/api/apps.permissions.request", query = {"scopes", "trigger_id"} },
    ["slack-app-configuration.apps_permissions_resources_list"] = { method = "GET", url = "https://slack.com/api/apps.permissions.resources.list", query = {"cursor", "limit"} },
    ["slack-app-configuration.apps_permissions_scopes_list"] = { method = "GET", url = "https://slack.com/api/apps.permissions.scopes.list" },
    ["slack-app-configuration.apps_permissions_users_list"] = { method = "GET", url = "https://slack.com/api/apps.permissions.users.list", query = {"cursor", "limit"} },
    ["slack-app-configuration.apps_permissions_users_request"] = { method = "GET", url = "https://slack.com/api/apps.permissions.users.request", query = {"scopes", "trigger_id", "user"} },
    ["slack-app-configuration.apps_uninstall"] = { method = "GET", url = "https://slack.com/api/apps.uninstall", query = {"client_id", "client_secret"} },
    ["slack-app-configuration.auth_revoke"] = { method = "GET", url = "https://slack.com/api/auth.revoke", query = {"test"} },
    ["slack-app-configuration.auth_test"] = { method = "GET", url = "https://slack.com/api/auth.test" },
    ["slack-app-configuration.bots_info"] = { method = "GET", url = "https://slack.com/api/bots.info", query = {"bot"} },
    ["slack-app-configuration.calls_add"] = { method = "POST", url = "https://slack.com/api/calls.add", body = {"created_by", "date_start", "desktop_app_join_url", "external_display_id", "external_unique_id", "join_url", "title", "users"} },
    ["slack-app-configuration.calls_end"] = { method = "POST", url = "https://slack.com/api/calls.end", body = {"duration", "id"} },
    ["slack-app-configuration.calls_info"] = { method = "GET", url = "https://slack.com/api/calls.info", query = {"id"} },
    ["slack-app-configuration.calls_participants_add"] = { method = "POST", url = "https://slack.com/api/calls.participants.add", body = {"id", "users"} },
    ["slack-app-configuration.calls_participants_remove"] = { method = "POST", url = "https://slack.com/api/calls.participants.remove", body = {"id", "users"} },
    ["slack-app-configuration.calls_update"] = { method = "POST", url = "https://slack.com/api/calls.update", body = {"desktop_app_join_url", "id", "join_url", "title"} },
    ["slack-app-configuration.chat_delete"] = { method = "POST", url = "https://slack.com/api/chat.delete", body = {"as_user", "channel", "ts"} },
    ["slack-app-configuration.chat_delete_scheduled_message"] = { method = "POST", url = "https://slack.com/api/chat.deleteScheduledMessage", body = {"as_user", "channel", "scheduled_message_id"} },
    ["slack-app-configuration.chat_get_permalink"] = { method = "GET", url = "https://slack.com/api/chat.getPermalink", query = {"channel", "message_ts"} },
    ["slack-app-configuration.chat_me_message"] = { method = "POST", url = "https://slack.com/api/chat.meMessage", body = {"channel", "text"} },
    ["slack-app-configuration.chat_post_ephemeral"] = { method = "POST", url = "https://slack.com/api/chat.postEphemeral", body = {"as_user", "attachments", "blocks", "channel", "icon_emoji", "icon_url", "link_names", "parse", "text", "thread_ts", "user", "username"} },
    ["slack-app-configuration.chat_post_message"] = { method = "POST", url = "https://slack.com/api/chat.postMessage", body = {"as_user", "attachments", "blocks", "channel", "icon_emoji", "icon_url", "link_names", "mrkdwn", "parse", "reply_broadcast", "text", "thread_ts", "unfurl_links", "unfurl_media", "username"} },
    ["slack-app-configuration.chat_schedule_message"] = { method = "POST", url = "https://slack.com/api/chat.scheduleMessage", body = {"as_user", "attachments", "blocks", "channel", "link_names", "parse", "post_at", "reply_broadcast", "text", "thread_ts", "unfurl_links", "unfurl_media"} },
    ["slack-app-configuration.chat_scheduled_messages_list"] = { method = "GET", url = "https://slack.com/api/chat.scheduledMessages.list", query = {"channel", "latest", "oldest", "limit", "cursor"} },
    ["slack-app-configuration.chat_unfurl"] = { method = "POST", url = "https://slack.com/api/chat.unfurl", body = {"channel", "ts", "unfurls", "user_auth_message", "user_auth_required", "user_auth_url"} },
    ["slack-app-configuration.chat_update"] = { method = "POST", url = "https://slack.com/api/chat.update", body = {"as_user", "attachments", "blocks", "channel", "link_names", "parse", "text", "ts"} },
    ["slack-app-configuration.conversations_archive"] = { method = "POST", url = "https://slack.com/api/conversations.archive", body = {"channel"} },
    ["slack-app-configuration.conversations_close"] = { method = "POST", url = "https://slack.com/api/conversations.close", body = {"channel"} },
    ["slack-app-configuration.conversations_create"] = { method = "POST", url = "https://slack.com/api/conversations.create", body = {"is_private", "name"} },
    ["slack-app-configuration.conversations_history"] = { method = "GET", url = "https://slack.com/api/conversations.history", query = {"channel", "latest", "oldest", "inclusive", "limit", "cursor"} },
    ["slack-app-configuration.conversations_info"] = { method = "GET", url = "https://slack.com/api/conversations.info", query = {"channel", "include_locale", "include_num_members"} },
    ["slack-app-configuration.conversations_invite"] = { method = "POST", url = "https://slack.com/api/conversations.invite", body = {"channel", "users"} },
    ["slack-app-configuration.conversations_join"] = { method = "POST", url = "https://slack.com/api/conversations.join", body = {"channel"} },
    ["slack-app-configuration.conversations_kick"] = { method = "POST", url = "https://slack.com/api/conversations.kick", body = {"channel", "user"} },
    ["slack-app-configuration.conversations_leave"] = { method = "POST", url = "https://slack.com/api/conversations.leave", body = {"channel"} },
    ["slack-app-configuration.conversations_list"] = { method = "GET", url = "https://slack.com/api/conversations.list", query = {"exclude_archived", "types", "limit", "cursor"} },
    ["slack-app-configuration.conversations_mark"] = { method = "POST", url = "https://slack.com/api/conversations.mark", body = {"channel", "ts"} },
    ["slack-app-configuration.conversations_members"] = { method = "GET", url = "https://slack.com/api/conversations.members", query = {"channel", "limit", "cursor"} },
    ["slack-app-configuration.conversations_open"] = { method = "POST", url = "https://slack.com/api/conversations.open", body = {"channel", "return_im", "users"} },
    ["slack-app-configuration.conversations_rename"] = { method = "POST", url = "https://slack.com/api/conversations.rename", body = {"channel", "name"} },
    ["slack-app-configuration.conversations_replies"] = { method = "GET", url = "https://slack.com/api/conversations.replies", query = {"channel", "ts", "latest", "oldest", "inclusive", "limit", "cursor"} },
    ["slack-app-configuration.conversations_set_purpose"] = { method = "POST", url = "https://slack.com/api/conversations.setPurpose", body = {"channel", "purpose"} },
    ["slack-app-configuration.conversations_set_topic"] = { method = "POST", url = "https://slack.com/api/conversations.setTopic", body = {"channel", "topic"} },
    ["slack-app-configuration.conversations_unarchive"] = { method = "POST", url = "https://slack.com/api/conversations.unarchive", body = {"channel"} },
    ["slack-app-configuration.dialog_open"] = { method = "GET", url = "https://slack.com/api/dialog.open", query = {"dialog", "trigger_id"} },
    ["slack-app-configuration.dnd_end_dnd"] = { method = "POST", url = "https://slack.com/api/dnd.endDnd" },
    ["slack-app-configuration.dnd_end_snooze"] = { method = "POST", url = "https://slack.com/api/dnd.endSnooze" },
    ["slack-app-configuration.dnd_info"] = { method = "GET", url = "https://slack.com/api/dnd.info", query = {"user"} },
    ["slack-app-configuration.dnd_set_snooze"] = { method = "POST", url = "https://slack.com/api/dnd.setSnooze", body = {"num_minutes"} },
    ["slack-app-configuration.dnd_team_info"] = { method = "GET", url = "https://slack.com/api/dnd.teamInfo", query = {"users"} },
    ["slack-app-configuration.emoji_list"] = { method = "GET", url = "https://slack.com/api/emoji.list" },
    ["slack-app-configuration.files_comments_delete"] = { method = "POST", url = "https://slack.com/api/files.comments.delete", body = {"file", "id"} },
    ["slack-app-configuration.files_delete"] = { method = "POST", url = "https://slack.com/api/files.delete", body = {"file"} },
    ["slack-app-configuration.files_info"] = { method = "GET", url = "https://slack.com/api/files.info", query = {"file", "count", "page", "limit", "cursor"} },
    ["slack-app-configuration.files_list"] = { method = "GET", url = "https://slack.com/api/files.list", query = {"user", "channel", "ts_from", "ts_to", "types", "count", "page", "show_files_hidden_by_limit"} },
    ["slack-app-configuration.files_remote_add"] = { method = "POST", url = "https://slack.com/api/files.remote.add", body = {"external_id", "external_url", "filetype", "indexable_file_contents", "preview_image", "title"} },
    ["slack-app-configuration.files_remote_info"] = { method = "GET", url = "https://slack.com/api/files.remote.info", query = {"file", "external_id"} },
    ["slack-app-configuration.files_remote_list"] = { method = "GET", url = "https://slack.com/api/files.remote.list", query = {"channel", "ts_from", "ts_to", "limit", "cursor"} },
    ["slack-app-configuration.files_remote_remove"] = { method = "POST", url = "https://slack.com/api/files.remote.remove", body = {"external_id", "file"} },
    ["slack-app-configuration.files_remote_share"] = { method = "GET", url = "https://slack.com/api/files.remote.share", query = {"file", "external_id", "channels"} },
    ["slack-app-configuration.files_remote_update"] = { method = "POST", url = "https://slack.com/api/files.remote.update", body = {"external_id", "external_url", "file", "filetype", "indexable_file_contents", "preview_image", "title"} },
    ["slack-app-configuration.files_revoke_public_url"] = { method = "POST", url = "https://slack.com/api/files.revokePublicURL", body = {"file"} },
    ["slack-app-configuration.files_shared_public_url"] = { method = "POST", url = "https://slack.com/api/files.sharedPublicURL", body = {"file"} },
    ["slack-app-configuration.files_upload"] = { method = "POST", url = "https://slack.com/api/files.upload", body = {"channels", "content", "file", "filename", "filetype", "initial_comment", "thread_ts", "title"} },
    ["slack-app-configuration.migration_exchange"] = { method = "GET", url = "https://slack.com/api/migration.exchange", query = {"users", "team_id", "to_old"} },
    ["slack-app-configuration.oauth_access"] = { method = "GET", url = "https://slack.com/api/oauth.access", query = {"client_id", "client_secret", "code", "redirect_uri", "single_channel"} },
    ["slack-app-configuration.oauth_token"] = { method = "GET", url = "https://slack.com/api/oauth.token", query = {"client_id", "client_secret", "code", "redirect_uri", "single_channel"} },
    ["slack-app-configuration.oauth_v2_access"] = { method = "GET", url = "https://slack.com/api/oauth.v2.access", query = {"client_id", "client_secret", "code", "redirect_uri"} },
    ["slack-app-configuration.pins_add"] = { method = "POST", url = "https://slack.com/api/pins.add", body = {"channel", "timestamp"} },
    ["slack-app-configuration.pins_list"] = { method = "GET", url = "https://slack.com/api/pins.list", query = {"channel"} },
    ["slack-app-configuration.pins_remove"] = { method = "POST", url = "https://slack.com/api/pins.remove", body = {"channel", "timestamp"} },
    ["slack-app-configuration.reactions_add"] = { method = "POST", url = "https://slack.com/api/reactions.add", body = {"channel", "name", "timestamp"} },
    ["slack-app-configuration.reactions_get"] = { method = "GET", url = "https://slack.com/api/reactions.get", query = {"channel", "file", "file_comment", "full", "timestamp"} },
    ["slack-app-configuration.reactions_list"] = { method = "GET", url = "https://slack.com/api/reactions.list", query = {"user", "full", "count", "page", "cursor", "limit"} },
    ["slack-app-configuration.reactions_remove"] = { method = "POST", url = "https://slack.com/api/reactions.remove", body = {"channel", "file", "file_comment", "name", "timestamp"} },
    ["slack-app-configuration.reminders_add"] = { method = "POST", url = "https://slack.com/api/reminders.add", body = {"text", "time", "user"} },
    ["slack-app-configuration.reminders_complete"] = { method = "POST", url = "https://slack.com/api/reminders.complete", body = {"reminder"} },
    ["slack-app-configuration.reminders_delete"] = { method = "POST", url = "https://slack.com/api/reminders.delete", body = {"reminder"} },
    ["slack-app-configuration.reminders_info"] = { method = "GET", url = "https://slack.com/api/reminders.info", query = {"reminder"} },
    ["slack-app-configuration.reminders_list"] = { method = "GET", url = "https://slack.com/api/reminders.list" },
    ["slack-app-configuration.rtm_connect"] = { method = "GET", url = "https://slack.com/api/rtm.connect", query = {"batch_presence_aware", "presence_sub"} },
    ["slack-app-configuration.search_messages"] = { method = "GET", url = "https://slack.com/api/search.messages", query = {"count", "highlight", "page", "query", "sort", "sort_dir"} },
    ["slack-app-configuration.stars_add"] = { method = "POST", url = "https://slack.com/api/stars.add", body = {"channel", "file", "file_comment", "timestamp"} },
    ["slack-app-configuration.stars_list"] = { method = "GET", url = "https://slack.com/api/stars.list", query = {"count", "page", "cursor", "limit"} },
    ["slack-app-configuration.stars_remove"] = { method = "POST", url = "https://slack.com/api/stars.remove", body = {"channel", "file", "file_comment", "timestamp"} },
    ["slack-app-configuration.team_access_logs"] = { method = "GET", url = "https://slack.com/api/team.accessLogs", query = {"before", "count", "page"} },
    ["slack-app-configuration.team_billable_info"] = { method = "GET", url = "https://slack.com/api/team.billableInfo", query = {"user"} },
    ["slack-app-configuration.team_info"] = { method = "GET", url = "https://slack.com/api/team.info", query = {"team"} },
    ["slack-app-configuration.team_integration_logs"] = { method = "GET", url = "https://slack.com/api/team.integrationLogs", query = {"app_id", "change_type", "count", "page", "service_id", "user"} },
    ["slack-app-configuration.team_profile_get"] = { method = "GET", url = "https://slack.com/api/team.profile.get", query = {"visibility"} },
    ["slack-app-configuration.usergroups_create"] = { method = "POST", url = "https://slack.com/api/usergroups.create", body = {"channels", "description", "handle", "include_count", "name"} },
    ["slack-app-configuration.usergroups_disable"] = { method = "POST", url = "https://slack.com/api/usergroups.disable", body = {"include_count", "usergroup"} },
    ["slack-app-configuration.usergroups_enable"] = { method = "POST", url = "https://slack.com/api/usergroups.enable", body = {"include_count", "usergroup"} },
    ["slack-app-configuration.usergroups_list"] = { method = "GET", url = "https://slack.com/api/usergroups.list", query = {"include_users", "include_count", "include_disabled"} },
    ["slack-app-configuration.usergroups_update"] = { method = "POST", url = "https://slack.com/api/usergroups.update", body = {"channels", "description", "handle", "include_count", "name", "usergroup"} },
    ["slack-app-configuration.usergroups_users_list"] = { method = "GET", url = "https://slack.com/api/usergroups.users.list", query = {"include_disabled", "usergroup"} },
    ["slack-app-configuration.usergroups_users_update"] = { method = "POST", url = "https://slack.com/api/usergroups.users.update", body = {"include_count", "usergroup", "users"} },
    ["slack-app-configuration.users_conversations"] = { method = "GET", url = "https://slack.com/api/users.conversations", query = {"user", "types", "exclude_archived", "limit", "cursor"} },
    ["slack-app-configuration.users_delete_photo"] = { method = "POST", url = "https://slack.com/api/users.deletePhoto" },
    ["slack-app-configuration.users_get_presence"] = { method = "GET", url = "https://slack.com/api/users.getPresence", query = {"user"} },
    ["slack-app-configuration.users_identity"] = { method = "GET", url = "https://slack.com/api/users.identity" },
    ["slack-app-configuration.users_info"] = { method = "GET", url = "https://slack.com/api/users.info", query = {"include_locale", "user"} },
    ["slack-app-configuration.users_list"] = { method = "GET", url = "https://slack.com/api/users.list", query = {"limit", "cursor", "include_locale"} },
    ["slack-app-configuration.users_lookup_by_email"] = { method = "GET", url = "https://slack.com/api/users.lookupByEmail", query = {"email"} },
    ["slack-app-configuration.users_profile_get"] = { method = "GET", url = "https://slack.com/api/users.profile.get", query = {"include_labels", "user"} },
    ["slack-app-configuration.users_profile_set"] = { method = "POST", url = "https://slack.com/api/users.profile.set", body = {"name", "profile", "user", "value"} },
    ["slack-app-configuration.users_set_active"] = { method = "POST", url = "https://slack.com/api/users.setActive" },
    ["slack-app-configuration.users_set_photo"] = { method = "POST", url = "https://slack.com/api/users.setPhoto", body = {"crop_w", "crop_x", "crop_y", "image"} },
    ["slack-app-configuration.users_set_presence"] = { method = "POST", url = "https://slack.com/api/users.setPresence", body = {"presence"} },
    ["slack-app-configuration.views_open"] = { method = "GET", url = "https://slack.com/api/views.open", query = {"trigger_id", "view"} },
    ["slack-app-configuration.views_publish"] = { method = "GET", url = "https://slack.com/api/views.publish", query = {"user_id", "view", "hash"} },
    ["slack-app-configuration.views_push"] = { method = "GET", url = "https://slack.com/api/views.push", query = {"trigger_id", "view"} },
    ["slack-app-configuration.views_update"] = { method = "GET", url = "https://slack.com/api/views.update", query = {"view_id", "external_id", "view", "hash"} },
    ["slack-app-configuration.workflows_step_completed"] = { method = "GET", url = "https://slack.com/api/workflows.stepCompleted", query = {"workflow_step_execute_id", "outputs"} },
    ["slack-app-configuration.workflows_step_failed"] = { method = "GET", url = "https://slack.com/api/workflows.stepFailed", query = {"workflow_step_execute_id", "error"} },
    ["slack-app-configuration.workflows_update_step"] = { method = "GET", url = "https://slack.com/api/workflows.updateStep", query = {"workflow_step_edit_id", "inputs", "outputs", "step_name", "step_image_url"} },
  },
}
