-- Discord Bot — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi_preview.json
-- Published by discord, the vendor's own GitHub organisation.
-- 246 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "discord-bot",
  name = "Discord Bot",
  base = "https://discord.com",
  docs = "https://nango.dev/docs/api-integrations/discord-bot",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bot {token}",
    env = "DISCORD_BOT_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["discord-bot.action_guild_join_request"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/requests/{request_id}", path = {"guild_id", "request_id"}, body = {"action", "rejection_reason"} },
    ["discord-bot.add_group_dm_user"] = { method = "PUT", url = "https://discord.com/api/v10/channels/{channel_id}/recipients/{user_id}", path = {"channel_id", "user_id"}, body = {"nick"} },
    ["discord-bot.add_guild_member"] = { method = "PUT", url = "https://discord.com/api/v10/guilds/{guild_id}/members/{user_id}", path = {"guild_id", "user_id"}, body = {"nick", "roles", "mute", "deaf", "flags"} },
    ["discord-bot.add_guild_member_role"] = { method = "PUT", url = "https://discord.com/api/v10/guilds/{guild_id}/members/{user_id}/roles/{role_id}", path = {"guild_id", "user_id", "role_id"} },
    ["discord-bot.add_invite_target_user"] = { method = "PUT", url = "https://discord.com/api/v10/invites/{code}/target-users/{user_id}", path = {"code", "user_id"} },
    ["discord-bot.add_lobby_member"] = { method = "PUT", url = "https://discord.com/api/v10/lobbies/{lobby_id}/members/{user_id}", path = {"lobby_id", "user_id"}, body = {"metadata", "flags", "additional_name"} },
    ["discord-bot.add_my_message_reaction"] = { method = "PUT", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me", path = {"channel_id", "message_id", "emoji_name"} },
    ["discord-bot.add_thread_member"] = { method = "PUT", url = "https://discord.com/api/v10/channels/{channel_id}/thread-members/{user_id}", path = {"channel_id", "user_id"} },
    ["discord-bot.applications_get_activity_instance"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/activity-instances/{instance_id}", path = {"application_id", "instance_id"} },
    ["discord-bot.ban_user_from_guild"] = { method = "PUT", url = "https://discord.com/api/v10/guilds/{guild_id}/bans/{user_id}", path = {"guild_id", "user_id"}, body = {"delete_message_seconds", "delete_message_days"} },
    ["discord-bot.bot_partner_sdk_token"] = { method = "POST", url = "https://discord.com/api/v10/partner-sdk/token/bot", body = {"provisional_user_id", "external_user_id", "preferred_global_name"} },
    ["discord-bot.bot_partner_sdk_unmerge_provisional_account"] = { method = "POST", url = "https://discord.com/api/v10/partner-sdk/provisional-accounts/unmerge/bot", body = {"external_user_id"} },
    ["discord-bot.bulk_add_invite_target_users"] = { method = "POST", url = "https://discord.com/api/v10/invites/{code}/target-users/bulk-add", path = {"code"}, body = {"user_ids"} },
    ["discord-bot.bulk_ban_users_from_guild"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/bulk-ban", path = {"guild_id"}, body = {"user_ids", "delete_message_seconds"} },
    ["discord-bot.bulk_delete_messages"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/messages/bulk-delete", path = {"channel_id"}, body = {"messages"} },
    ["discord-bot.bulk_remove_invite_target_users"] = { method = "POST", url = "https://discord.com/api/v10/invites/{code}/target-users/bulk-delete", path = {"code"}, body = {"user_ids"} },
    ["discord-bot.bulk_set_application_commands"] = { method = "PUT", url = "https://discord.com/api/v10/applications/{application_id}/commands", path = {"application_id"} },
    ["discord-bot.bulk_set_guild_application_commands"] = { method = "PUT", url = "https://discord.com/api/v10/applications/{application_id}/guilds/{guild_id}/commands", path = {"application_id", "guild_id"} },
    ["discord-bot.bulk_update_guild_channels"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/channels", path = {"guild_id"} },
    ["discord-bot.bulk_update_guild_roles"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/roles", path = {"guild_id"} },
    ["discord-bot.bulk_update_lobby_members"] = { method = "POST", url = "https://discord.com/api/v10/lobbies/{lobby_id}/members/bulk", path = {"lobby_id"} },
    ["discord-bot.consume_entitlement"] = { method = "POST", url = "https://discord.com/api/v10/applications/{application_id}/entitlements/{entitlement_id}/consume", path = {"application_id", "entitlement_id"} },
    ["discord-bot.count_guild_scheduled_event_users"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users/counts", path = {"guild_id", "guild_scheduled_event_id"}, query = {"guild_scheduled_event_exception_ids"} },
    ["discord-bot.create_application_command"] = { method = "POST", url = "https://discord.com/api/v10/applications/{application_id}/commands", path = {"application_id"}, body = {"name", "name_localizations", "description", "description_localizations", "options", "default_member_permissions", "dm_permission", "contexts", "integration_types", "handler", "type"} },
    ["discord-bot.create_application_emoji"] = { method = "POST", url = "https://discord.com/api/v10/applications/{application_id}/emojis", path = {"application_id"}, body = {"name", "image"} },
    ["discord-bot.create_auto_moderation_rule"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/auto-moderation/rules", path = {"guild_id"} },
    ["discord-bot.create_channel_invite"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/invites", path = {"channel_id"} },
    ["discord-bot.create_dm"] = { method = "POST", url = "https://discord.com/api/v10/users/@me/channels", body = {"recipient_id", "access_tokens", "nicks"} },
    ["discord-bot.create_entitlement"] = { method = "POST", url = "https://discord.com/api/v10/applications/{application_id}/entitlements", path = {"application_id"}, body = {"sku_id", "owner_id", "owner_type"} },
    ["discord-bot.create_guild_application_command"] = { method = "POST", url = "https://discord.com/api/v10/applications/{application_id}/guilds/{guild_id}/commands", path = {"application_id", "guild_id"}, body = {"name", "name_localizations", "description", "description_localizations", "options", "default_member_permissions", "dm_permission", "contexts", "integration_types", "handler", "type"} },
    ["discord-bot.create_guild_channel"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/channels", path = {"guild_id"}, body = {"type", "name", "position", "topic", "bitrate", "user_limit", "nsfw", "rate_limit_per_user", "parent_id", "permission_overwrites", "rtc_region", "video_quality_mode", "default_auto_archive_duration", "default_reaction_emoji", "default_thread_rate_limit_per_user", "default_sort_order", "default_forum_layout", "default_tag_setting", "available_tags"} },
    ["discord-bot.create_guild_emoji"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/emojis", path = {"guild_id"}, body = {"name", "image", "roles"} },
    ["discord-bot.create_guild_role"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/roles", path = {"guild_id"}, body = {"name", "permissions", "color", "colors", "hoist", "mentionable", "icon", "unicode_emoji"} },
    ["discord-bot.create_guild_scheduled_event"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events", path = {"guild_id"} },
    ["discord-bot.create_guild_scheduled_event_exception"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions", path = {"guild_id", "guild_scheduled_event_id"}, body = {"scheduled_start_time", "scheduled_end_time", "original_scheduled_start_time", "is_canceled"} },
    ["discord-bot.create_guild_soundboard_sound"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/soundboard-sounds", path = {"guild_id"}, body = {"name", "volume", "emoji_id", "emoji_name", "sound"} },
    ["discord-bot.create_guild_sticker"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/stickers", path = {"guild_id"}, body = {"name", "tags", "description", "file"} },
    ["discord-bot.create_guild_template"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/templates", path = {"guild_id"}, body = {"name", "description"} },
    ["discord-bot.create_interaction_response"] = { method = "POST", url = "https://discord.com/api/v10/interactions/{interaction_id}/{interaction_token}/callback", path = {"interaction_id", "interaction_token"}, query = {"with_response"} },
    ["discord-bot.create_linked_lobby_guild_invite_for_self"] = { method = "POST", url = "https://discord.com/api/v10/lobbies/{lobby_id}/members/@me/invites", path = {"lobby_id"} },
    ["discord-bot.create_linked_lobby_guild_invite_for_user"] = { method = "POST", url = "https://discord.com/api/v10/lobbies/{lobby_id}/members/{user_id}/invites", path = {"lobby_id", "user_id"} },
    ["discord-bot.create_lobby"] = { method = "POST", url = "https://discord.com/api/v10/lobbies", body = {"idle_timeout_seconds", "members", "metadata", "flags", "override_event_webhooks_url"} },
    ["discord-bot.create_lobby_message"] = { method = "POST", url = "https://discord.com/api/v10/lobbies/{lobby_id}/messages", path = {"lobby_id"}, body = {"content", "embeds", "allowed_mentions", "sticker_ids", "components", "flags", "attachments", "poll", "shared_client_theme", "message_reference", "nonce", "enforce_nonce", "tts"} },
    ["discord-bot.create_message"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/messages", path = {"channel_id"}, body = {"content", "embeds", "allowed_mentions", "sticker_ids", "components", "flags", "attachments", "poll", "shared_client_theme", "message_reference", "nonce", "enforce_nonce", "tts"} },
    ["discord-bot.create_or_join_lobby"] = { method = "PUT", url = "https://discord.com/api/v10/lobbies", body = {"idle_timeout_seconds", "lobby_metadata", "member_metadata", "flags"} },
    ["discord-bot.create_pin"] = { method = "PUT", url = "https://discord.com/api/v10/channels/{channel_id}/messages/pins/{message_id}", path = {"channel_id", "message_id"} },
    ["discord-bot.create_stage_instance"] = { method = "POST", url = "https://discord.com/api/v10/stage-instances", body = {"topic", "channel_id", "privacy_level", "guild_scheduled_event_id", "send_start_notification"} },
    ["discord-bot.create_thread"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/threads", path = {"channel_id"} },
    ["discord-bot.create_thread_from_message"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}/threads", path = {"channel_id", "message_id"}, body = {"name", "auto_archive_duration", "rate_limit_per_user"} },
    ["discord-bot.create_webhook"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/webhooks", path = {"channel_id"}, body = {"name", "avatar"} },
    ["discord-bot.crosspost_message"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}/crosspost", path = {"channel_id", "message_id"} },
    ["discord-bot.delete_all_message_reactions"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}/reactions", path = {"channel_id", "message_id"} },
    ["discord-bot.delete_all_message_reactions_by_emoji"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}", path = {"channel_id", "message_id", "emoji_name"} },
    ["discord-bot.delete_application_command"] = { method = "DELETE", url = "https://discord.com/api/v10/applications/{application_id}/commands/{command_id}", path = {"application_id", "command_id"} },
    ["discord-bot.delete_application_emoji"] = { method = "DELETE", url = "https://discord.com/api/v10/applications/{application_id}/emojis/{emoji_id}", path = {"application_id", "emoji_id"} },
    ["discord-bot.delete_application_user_role_connection"] = { method = "DELETE", url = "https://discord.com/api/v10/users/@me/applications/{application_id}/role-connection", path = {"application_id"} },
    ["discord-bot.delete_auto_moderation_rule"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/auto-moderation/rules/{rule_id}", path = {"guild_id", "rule_id"} },
    ["discord-bot.delete_channel"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}", path = {"channel_id"} },
    ["discord-bot.delete_channel_permission_overwrite"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/permissions/{overwrite_id}", path = {"channel_id", "overwrite_id"} },
    ["discord-bot.delete_entitlement"] = { method = "DELETE", url = "https://discord.com/api/v10/applications/{application_id}/entitlements/{entitlement_id}", path = {"application_id", "entitlement_id"} },
    ["discord-bot.delete_group_dm_user"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/recipients/{user_id}", path = {"channel_id", "user_id"} },
    ["discord-bot.delete_guild_application_command"] = { method = "DELETE", url = "https://discord.com/api/v10/applications/{application_id}/guilds/{guild_id}/commands/{command_id}", path = {"application_id", "guild_id", "command_id"} },
    ["discord-bot.delete_guild_emoji"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/emojis/{emoji_id}", path = {"guild_id", "emoji_id"} },
    ["discord-bot.delete_guild_integration"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/integrations/{integration_id}", path = {"guild_id", "integration_id"} },
    ["discord-bot.delete_guild_member"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/members/{user_id}", path = {"guild_id", "user_id"} },
    ["discord-bot.delete_guild_member_role"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/members/{user_id}/roles/{role_id}", path = {"guild_id", "user_id", "role_id"} },
    ["discord-bot.delete_guild_role"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/roles/{role_id}", path = {"guild_id", "role_id"} },
    ["discord-bot.delete_guild_scheduled_event"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}", path = {"guild_id", "guild_scheduled_event_id"} },
    ["discord-bot.delete_guild_scheduled_event_exception"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}", path = {"guild_id", "guild_scheduled_event_id", "exception_id"} },
    ["discord-bot.delete_guild_soundboard_sound"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/soundboard-sounds/{sound_id}", path = {"guild_id", "sound_id"} },
    ["discord-bot.delete_guild_sticker"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/stickers/{sticker_id}", path = {"guild_id", "sticker_id"} },
    ["discord-bot.delete_guild_template"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/templates/{code}", path = {"guild_id", "code"} },
    ["discord-bot.delete_lobby"] = { method = "DELETE", url = "https://discord.com/api/v10/lobbies/{lobby_id}", path = {"lobby_id"} },
    ["discord-bot.delete_lobby_member"] = { method = "DELETE", url = "https://discord.com/api/v10/lobbies/{lobby_id}/members/{user_id}", path = {"lobby_id", "user_id"} },
    ["discord-bot.delete_message"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}", path = {"channel_id", "message_id"} },
    ["discord-bot.delete_my_message_reaction"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me", path = {"channel_id", "message_id", "emoji_name"} },
    ["discord-bot.delete_original_webhook_message"] = { method = "DELETE", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}/messages/@original", path = {"webhook_id", "webhook_token"}, query = {"thread_id"} },
    ["discord-bot.delete_pin"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/messages/pins/{message_id}", path = {"channel_id", "message_id"} },
    ["discord-bot.delete_stage_instance"] = { method = "DELETE", url = "https://discord.com/api/v10/stage-instances/{channel_id}", path = {"channel_id"} },
    ["discord-bot.delete_thread_member"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/thread-members/{user_id}", path = {"channel_id", "user_id"} },
    ["discord-bot.delete_user_message_reaction"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/{user_id}", path = {"channel_id", "message_id", "emoji_name", "user_id"} },
    ["discord-bot.delete_webhook"] = { method = "DELETE", url = "https://discord.com/api/v10/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["discord-bot.delete_webhook_by_token"] = { method = "DELETE", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}", path = {"webhook_id", "webhook_token"} },
    ["discord-bot.delete_webhook_message"] = { method = "DELETE", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}", path = {"webhook_id", "webhook_token", "message_id"}, query = {"thread_id"} },
    ["discord-bot.deprecated_create_pin"] = { method = "PUT", url = "https://discord.com/api/v10/channels/{channel_id}/pins/{message_id}", path = {"channel_id", "message_id"} },
    ["discord-bot.deprecated_delete_pin"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/pins/{message_id}", path = {"channel_id", "message_id"} },
    ["discord-bot.deprecated_list_pins"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/pins", path = {"channel_id"} },
    ["discord-bot.edit_lobby"] = { method = "PATCH", url = "https://discord.com/api/v10/lobbies/{lobby_id}", path = {"lobby_id"}, body = {"idle_timeout_seconds", "metadata", "members", "flags", "override_event_webhooks_url"} },
    ["discord-bot.edit_lobby_channel_link"] = { method = "PATCH", url = "https://discord.com/api/v10/lobbies/{lobby_id}/channel-linking", path = {"lobby_id"}, body = {"channel_id"} },
    ["discord-bot.execute_github_compatible_webhook"] = { method = "POST", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}/github", path = {"webhook_id", "webhook_token"}, query = {"wait", "thread_id"}, body = {"action", "ref", "ref_type", "comment", "issue", "pull_request", "repository", "forkee", "sender", "member", "release", "head_commit", "commits", "forced", "compare", "review", "check_run", "check_suite", "discussion", "answer"} },
    ["discord-bot.execute_slack_compatible_webhook"] = { method = "POST", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}/slack", path = {"webhook_id", "webhook_token"}, query = {"wait", "thread_id"}, body = {"text", "username", "icon_url", "attachments"} },
    ["discord-bot.execute_webhook"] = { method = "POST", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}", path = {"webhook_id", "webhook_token"}, query = {"wait", "thread_id", "with_components"} },
    ["discord-bot.follow_channel"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/followers", path = {"channel_id"}, body = {"webhook_channel_id"} },
    ["discord-bot.get_active_guild_threads"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/threads/active", path = {"guild_id"} },
    ["discord-bot.get_answer_voters"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/polls/{message_id}/answers/{answer_id}", path = {"channel_id", "message_id", "answer_id"}, query = {"after", "limit"} },
    ["discord-bot.get_application"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}", path = {"application_id"} },
    ["discord-bot.get_application_command"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/commands/{command_id}", path = {"application_id", "command_id"} },
    ["discord-bot.get_application_emoji"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/emojis/{emoji_id}", path = {"application_id", "emoji_id"} },
    ["discord-bot.get_application_role_connections_metadata"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/role-connections/metadata", path = {"application_id"} },
    ["discord-bot.get_application_user_role_connection"] = { method = "GET", url = "https://discord.com/api/v10/users/@me/applications/{application_id}/role-connection", path = {"application_id"} },
    ["discord-bot.get_auto_moderation_rule"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/auto-moderation/rules/{rule_id}", path = {"guild_id", "rule_id"} },
    ["discord-bot.get_bot_gateway"] = { method = "GET", url = "https://discord.com/api/v10/gateway/bot" },
    ["discord-bot.get_channel"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}", path = {"channel_id"} },
    ["discord-bot.get_current_user_application_entitlements"] = { method = "GET", url = "https://discord.com/api/v10/users/@me/applications/{application_id}/entitlements", path = {"application_id"}, query = {"sku_ids", "exclude_consumed"} },
    ["discord-bot.get_entitlement"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/entitlements/{entitlement_id}", path = {"application_id", "entitlement_id"} },
    ["discord-bot.get_entitlements"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/entitlements", path = {"application_id"}, query = {"user_id", "sku_ids", "guild_id", "before", "after", "limit", "exclude_ended", "exclude_deleted", "only_active"} },
    ["discord-bot.get_gateway"] = { method = "GET", url = "https://discord.com/api/v10/gateway" },
    ["discord-bot.get_guild"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}", path = {"guild_id"}, query = {"with_counts"} },
    ["discord-bot.get_guild_application_command"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/guilds/{guild_id}/commands/{command_id}", path = {"application_id", "guild_id", "command_id"} },
    ["discord-bot.get_guild_application_command_permissions"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions", path = {"application_id", "guild_id", "command_id"} },
    ["discord-bot.get_guild_ban"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/bans/{user_id}", path = {"guild_id", "user_id"} },
    ["discord-bot.get_guild_emoji"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/emojis/{emoji_id}", path = {"guild_id", "emoji_id"} },
    ["discord-bot.get_guild_join_requests"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/requests", path = {"guild_id"}, query = {"status", "limit", "before", "after"} },
    ["discord-bot.get_guild_member"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/members/{user_id}", path = {"guild_id", "user_id"} },
    ["discord-bot.get_guild_new_member_welcome"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/new-member-welcome", path = {"guild_id"} },
    ["discord-bot.get_guild_preview"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/preview", path = {"guild_id"} },
    ["discord-bot.get_guild_role"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/roles/{role_id}", path = {"guild_id", "role_id"} },
    ["discord-bot.get_guild_scheduled_event"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}", path = {"guild_id", "guild_scheduled_event_id"}, query = {"with_user_count"} },
    ["discord-bot.get_guild_soundboard_sound"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/soundboard-sounds/{sound_id}", path = {"guild_id", "sound_id"} },
    ["discord-bot.get_guild_sticker"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/stickers/{sticker_id}", path = {"guild_id", "sticker_id"} },
    ["discord-bot.get_guild_template"] = { method = "GET", url = "https://discord.com/api/v10/guilds/templates/{code}", path = {"code"} },
    ["discord-bot.get_guild_vanity_url"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/vanity-url", path = {"guild_id"} },
    ["discord-bot.get_guild_webhooks"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/webhooks", path = {"guild_id"} },
    ["discord-bot.get_guild_welcome_screen"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/welcome-screen", path = {"guild_id"} },
    ["discord-bot.get_guild_widget"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/widget.json", path = {"guild_id"} },
    ["discord-bot.get_guild_widget_png"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/widget.png", path = {"guild_id"}, query = {"style"} },
    ["discord-bot.get_guild_widget_settings"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/widget", path = {"guild_id"} },
    ["discord-bot.get_guilds_onboarding"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/onboarding", path = {"guild_id"} },
    ["discord-bot.get_invite_target_users"] = { method = "GET", url = "https://discord.com/api/v10/invites/{code}/target-users", path = {"code"} },
    ["discord-bot.get_invite_target_users_job_status"] = { method = "GET", url = "https://discord.com/api/v10/invites/{code}/target-users/job-status", path = {"code"} },
    ["discord-bot.get_lobby"] = { method = "GET", url = "https://discord.com/api/v10/lobbies/{lobby_id}", path = {"lobby_id"} },
    ["discord-bot.get_lobby_messages"] = { method = "GET", url = "https://discord.com/api/v10/lobbies/{lobby_id}/messages", path = {"lobby_id"}, query = {"limit"} },
    ["discord-bot.get_message"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}", path = {"channel_id", "message_id"} },
    ["discord-bot.get_my_application"] = { method = "GET", url = "https://discord.com/api/v10/applications/@me" },
    ["discord-bot.get_my_guild_member"] = { method = "GET", url = "https://discord.com/api/v10/users/@me/guilds/{guild_id}/member", path = {"guild_id"} },
    ["discord-bot.get_my_oauth2_application"] = { method = "GET", url = "https://discord.com/api/v10/oauth2/applications/@me" },
    ["discord-bot.get_my_oauth2_authorization"] = { method = "GET", url = "https://discord.com/api/v10/oauth2/@me" },
    ["discord-bot.get_my_user"] = { method = "GET", url = "https://discord.com/api/v10/users/@me" },
    ["discord-bot.get_openid_connect_userinfo"] = { method = "GET", url = "https://discord.com/api/v10/oauth2/userinfo" },
    ["discord-bot.get_original_webhook_message"] = { method = "GET", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}/messages/@original", path = {"webhook_id", "webhook_token"}, query = {"thread_id"} },
    ["discord-bot.get_public_keys"] = { method = "GET", url = "https://discord.com/api/v10/oauth2/keys" },
    ["discord-bot.get_self_voice_state"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/voice-states/@me", path = {"guild_id"} },
    ["discord-bot.get_sku_subscription"] = { method = "GET", url = "https://discord.com/api/v10/skus/{sku_id}/subscriptions/{subscription_id}", path = {"sku_id", "subscription_id"}, query = {"user_id"} },
    ["discord-bot.get_sku_subscriptions"] = { method = "GET", url = "https://discord.com/api/v10/skus/{sku_id}/subscriptions", path = {"sku_id"}, query = {"before", "after", "limit", "user_id"} },
    ["discord-bot.get_soundboard_default_sounds"] = { method = "GET", url = "https://discord.com/api/v10/soundboard-default-sounds" },
    ["discord-bot.get_stage_instance"] = { method = "GET", url = "https://discord.com/api/v10/stage-instances/{channel_id}", path = {"channel_id"} },
    ["discord-bot.get_sticker"] = { method = "GET", url = "https://discord.com/api/v10/stickers/{sticker_id}", path = {"sticker_id"} },
    ["discord-bot.get_sticker_pack"] = { method = "GET", url = "https://discord.com/api/v10/sticker-packs/{pack_id}", path = {"pack_id"} },
    ["discord-bot.get_thread_member"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/thread-members/{user_id}", path = {"channel_id", "user_id"}, query = {"with_member"} },
    ["discord-bot.get_user"] = { method = "GET", url = "https://discord.com/api/v10/users/{user_id}", path = {"user_id"} },
    ["discord-bot.get_voice_state"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/voice-states/{user_id}", path = {"guild_id", "user_id"} },
    ["discord-bot.get_webhook"] = { method = "GET", url = "https://discord.com/api/v10/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["discord-bot.get_webhook_by_token"] = { method = "GET", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}", path = {"webhook_id", "webhook_token"} },
    ["discord-bot.get_webhook_message"] = { method = "GET", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}", path = {"webhook_id", "webhook_token", "message_id"}, query = {"thread_id"} },
    ["discord-bot.guild_role_member_counts"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/roles/member-counts", path = {"guild_id"} },
    ["discord-bot.guild_search"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/messages/search", path = {"guild_id"}, query = {"sort_by", "sort_order", "content", "slop", "contents", "author_id", "author_type", "mentions", "mentions_role_id", "replied_to_user_id", "replied_to_message_id", "mention_everyone", "min_id", "max_id", "limit", "offset", "has", "link_hostname", "embed_provider", "embed_type", "attachment_extension", "attachment_filename", "pinned", "include_nsfw", "channel_id"} },
    ["discord-bot.invite_resolve"] = { method = "GET", url = "https://discord.com/api/v10/invites/{code}", path = {"code"}, query = {"with_counts", "guild_scheduled_event_id", "target_channel_id", "target_message_id"} },
    ["discord-bot.invite_revoke"] = { method = "DELETE", url = "https://discord.com/api/v10/invites/{code}", path = {"code"} },
    ["discord-bot.join_thread"] = { method = "PUT", url = "https://discord.com/api/v10/channels/{channel_id}/thread-members/@me", path = {"channel_id"} },
    ["discord-bot.leave_guild"] = { method = "DELETE", url = "https://discord.com/api/v10/users/@me/guilds/{guild_id}", path = {"guild_id"} },
    ["discord-bot.leave_lobby"] = { method = "DELETE", url = "https://discord.com/api/v10/lobbies/{lobby_id}/members/@me", path = {"lobby_id"} },
    ["discord-bot.leave_thread"] = { method = "DELETE", url = "https://discord.com/api/v10/channels/{channel_id}/thread-members/@me", path = {"channel_id"} },
    ["discord-bot.list_application_commands"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/commands", path = {"application_id"}, query = {"with_localizations"} },
    ["discord-bot.list_application_emojis"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/emojis", path = {"application_id"} },
    ["discord-bot.list_auto_moderation_rules"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/auto-moderation/rules", path = {"guild_id"} },
    ["discord-bot.list_channel_invites"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/invites", path = {"channel_id"} },
    ["discord-bot.list_channel_webhooks"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/webhooks", path = {"channel_id"} },
    ["discord-bot.list_guild_application_command_permissions"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/guilds/{guild_id}/commands/permissions", path = {"application_id", "guild_id"} },
    ["discord-bot.list_guild_application_commands"] = { method = "GET", url = "https://discord.com/api/v10/applications/{application_id}/guilds/{guild_id}/commands", path = {"application_id", "guild_id"}, query = {"with_localizations"} },
    ["discord-bot.list_guild_audit_log_entries"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/audit-logs", path = {"guild_id"}, query = {"user_id", "target_id", "action_type", "before", "after", "limit"} },
    ["discord-bot.list_guild_bans"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/bans", path = {"guild_id"}, query = {"limit", "before", "after"} },
    ["discord-bot.list_guild_channels"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/channels", path = {"guild_id"} },
    ["discord-bot.list_guild_emojis"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/emojis", path = {"guild_id"} },
    ["discord-bot.list_guild_integrations"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/integrations", path = {"guild_id"} },
    ["discord-bot.list_guild_invites"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/invites", path = {"guild_id"} },
    ["discord-bot.list_guild_members"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/members", path = {"guild_id"}, query = {"limit", "after"} },
    ["discord-bot.list_guild_roles"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/roles", path = {"guild_id"} },
    ["discord-bot.list_guild_scheduled_event_exception_users"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/{guild_scheduled_event_exception_id}/users", path = {"guild_id", "guild_scheduled_event_id", "guild_scheduled_event_exception_id"}, query = {"with_member", "limit", "before", "after"} },
    ["discord-bot.list_guild_scheduled_event_users"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users", path = {"guild_id", "guild_scheduled_event_id"}, query = {"with_member", "limit", "before", "after"} },
    ["discord-bot.list_guild_scheduled_events"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events", path = {"guild_id"}, query = {"with_user_count"} },
    ["discord-bot.list_guild_soundboard_sounds"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/soundboard-sounds", path = {"guild_id"} },
    ["discord-bot.list_guild_stickers"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/stickers", path = {"guild_id"} },
    ["discord-bot.list_guild_templates"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/templates", path = {"guild_id"} },
    ["discord-bot.list_guild_voice_regions"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/regions", path = {"guild_id"} },
    ["discord-bot.list_message_reactions_by_emoji"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}", path = {"channel_id", "message_id", "emoji_name"}, query = {"after", "limit", "type"} },
    ["discord-bot.list_messages"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/messages", path = {"channel_id"}, query = {"around", "before", "after", "limit"} },
    ["discord-bot.list_my_connections"] = { method = "GET", url = "https://discord.com/api/v10/users/@me/connections" },
    ["discord-bot.list_my_guilds"] = { method = "GET", url = "https://discord.com/api/v10/users/@me/guilds", query = {"before", "after", "limit", "shard", "with_counts"} },
    ["discord-bot.list_my_private_archived_threads"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/users/@me/threads/archived/private", path = {"channel_id"}, query = {"before", "limit"} },
    ["discord-bot.list_pins"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/messages/pins", path = {"channel_id"}, query = {"before", "limit"} },
    ["discord-bot.list_private_archived_threads"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/threads/archived/private", path = {"channel_id"}, query = {"before", "limit"} },
    ["discord-bot.list_public_archived_threads"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/threads/archived/public", path = {"channel_id"}, query = {"before", "limit"} },
    ["discord-bot.list_sticker_packs"] = { method = "GET", url = "https://discord.com/api/v10/sticker-packs" },
    ["discord-bot.list_thread_members"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/thread-members", path = {"channel_id"}, query = {"with_member", "limit", "after"} },
    ["discord-bot.list_voice_regions"] = { method = "GET", url = "https://discord.com/api/v10/voice/regions" },
    ["discord-bot.partner_sdk_token"] = { method = "POST", url = "https://discord.com/api/v10/partner-sdk/token", body = {"client_id", "client_secret", "external_auth_token", "external_auth_type"} },
    ["discord-bot.partner_sdk_unmerge_provisional_account"] = { method = "POST", url = "https://discord.com/api/v10/partner-sdk/provisional-accounts/unmerge", body = {"client_id", "client_secret", "external_auth_token", "external_auth_type"} },
    ["discord-bot.poll_expire"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/polls/{message_id}/expire", path = {"channel_id", "message_id"} },
    ["discord-bot.preview_prune_guild"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/prune", path = {"guild_id"}, query = {"days", "include_roles"} },
    ["discord-bot.prune_guild"] = { method = "POST", url = "https://discord.com/api/v10/guilds/{guild_id}/prune", path = {"guild_id"}, body = {"days", "compute_prune_count", "include_roles"} },
    ["discord-bot.put_guilds_onboarding"] = { method = "PUT", url = "https://discord.com/api/v10/guilds/{guild_id}/onboarding", path = {"guild_id"}, body = {"prompts", "enabled", "default_channel_ids", "mode"} },
    ["discord-bot.remove_invite_target_user"] = { method = "DELETE", url = "https://discord.com/api/v10/invites/{code}/target-users/{user_id}", path = {"code", "user_id"} },
    ["discord-bot.search_guild_members"] = { method = "GET", url = "https://discord.com/api/v10/guilds/{guild_id}/members/search", path = {"guild_id"}, query = {"limit", "query"} },
    ["discord-bot.send_soundboard_sound"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/send-soundboard-sound", path = {"channel_id"}, body = {"sound_id", "source_guild_id"} },
    ["discord-bot.set_channel_permission_overwrite"] = { method = "PUT", url = "https://discord.com/api/v10/channels/{channel_id}/permissions/{overwrite_id}", path = {"channel_id", "overwrite_id"}, body = {"type", "allow", "deny"} },
    ["discord-bot.set_guild_application_command_permissions"] = { method = "PUT", url = "https://discord.com/api/v10/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions", path = {"application_id", "guild_id", "command_id"}, body = {"permissions"} },
    ["discord-bot.sync_guild_template"] = { method = "PUT", url = "https://discord.com/api/v10/guilds/{guild_id}/templates/{code}", path = {"guild_id", "code"} },
    ["discord-bot.thread_search"] = { method = "GET", url = "https://discord.com/api/v10/channels/{channel_id}/threads/search", path = {"channel_id"}, query = {"name", "slop", "min_id", "max_id", "tag", "tag_setting", "archived", "sort_by", "sort_order", "limit", "offset"} },
    ["discord-bot.trigger_typing_indicator"] = { method = "POST", url = "https://discord.com/api/v10/channels/{channel_id}/typing", path = {"channel_id"} },
    ["discord-bot.unban_user_from_guild"] = { method = "DELETE", url = "https://discord.com/api/v10/guilds/{guild_id}/bans/{user_id}", path = {"guild_id", "user_id"} },
    ["discord-bot.update_application"] = { method = "PATCH", url = "https://discord.com/api/v10/applications/{application_id}", path = {"application_id"}, body = {"description", "icon", "cover_image", "team_id", "flags", "interactions_endpoint_url", "explicit_content_filter", "max_participants", "type", "tags", "custom_install_url", "install_params", "role_connections_verification_url", "integration_types_config", "event_webhooks_status", "event_webhooks_url", "event_webhooks_types"} },
    ["discord-bot.update_application_command"] = { method = "PATCH", url = "https://discord.com/api/v10/applications/{application_id}/commands/{command_id}", path = {"application_id", "command_id"}, body = {"name", "name_localizations", "description", "description_localizations", "options", "default_member_permissions", "dm_permission", "contexts", "integration_types", "handler"} },
    ["discord-bot.update_application_emoji"] = { method = "PATCH", url = "https://discord.com/api/v10/applications/{application_id}/emojis/{emoji_id}", path = {"application_id", "emoji_id"}, body = {"name"} },
    ["discord-bot.update_application_role_connections_metadata"] = { method = "PUT", url = "https://discord.com/api/v10/applications/{application_id}/role-connections/metadata", path = {"application_id"} },
    ["discord-bot.update_application_user_role_connection"] = { method = "PUT", url = "https://discord.com/api/v10/users/@me/applications/{application_id}/role-connection", path = {"application_id"}, body = {"platform_name", "platform_username", "metadata"} },
    ["discord-bot.update_auto_moderation_rule"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/auto-moderation/rules/{rule_id}", path = {"guild_id", "rule_id"} },
    ["discord-bot.update_channel"] = { method = "PATCH", url = "https://discord.com/api/v10/channels/{channel_id}", path = {"channel_id"} },
    ["discord-bot.update_guild"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}", path = {"guild_id"}, body = {"name", "description", "region", "icon", "verification_level", "default_message_notifications", "explicit_content_filter", "preferred_locale", "afk_timeout", "afk_channel_id", "system_channel_id", "splash", "banner", "system_channel_flags", "features", "discovery_splash", "home_header", "rules_channel_id", "safety_alerts_channel_id", "public_updates_channel_id", "premium_progress_bar_enabled"} },
    ["discord-bot.update_guild_application_command"] = { method = "PATCH", url = "https://discord.com/api/v10/applications/{application_id}/guilds/{guild_id}/commands/{command_id}", path = {"application_id", "guild_id", "command_id"}, body = {"name", "name_localizations", "description", "description_localizations", "options", "default_member_permissions", "dm_permission", "contexts", "integration_types", "handler"} },
    ["discord-bot.update_guild_emoji"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/emojis/{emoji_id}", path = {"guild_id", "emoji_id"}, body = {"name", "roles"} },
    ["discord-bot.update_guild_incident_actions"] = { method = "PUT", url = "https://discord.com/api/v10/guilds/{guild_id}/incident-actions", path = {"guild_id"}, body = {"invites_disabled_until", "dms_disabled_until"} },
    ["discord-bot.update_guild_member"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/members/{user_id}", path = {"guild_id", "user_id"}, body = {"nick", "roles", "mute", "deaf", "channel_id", "communication_disabled_until", "flags"} },
    ["discord-bot.update_guild_role"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/roles/{role_id}", path = {"guild_id", "role_id"}, body = {"name", "permissions", "color", "colors", "hoist", "mentionable", "icon", "unicode_emoji"} },
    ["discord-bot.update_guild_scheduled_event"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}", path = {"guild_id", "guild_scheduled_event_id"} },
    ["discord-bot.update_guild_scheduled_event_exception"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}", path = {"guild_id", "guild_scheduled_event_id", "exception_id"}, body = {"scheduled_start_time", "scheduled_end_time", "is_canceled"} },
    ["discord-bot.update_guild_soundboard_sound"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/soundboard-sounds/{sound_id}", path = {"guild_id", "sound_id"}, body = {"name", "volume", "emoji_id", "emoji_name"} },
    ["discord-bot.update_guild_sticker"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/stickers/{sticker_id}", path = {"guild_id", "sticker_id"}, body = {"name", "tags", "description"} },
    ["discord-bot.update_guild_template"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/templates/{code}", path = {"guild_id", "code"}, body = {"name", "description"} },
    ["discord-bot.update_guild_welcome_screen"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/welcome-screen", path = {"guild_id"}, body = {"description", "welcome_channels", "enabled"} },
    ["discord-bot.update_guild_widget_settings"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/widget", path = {"guild_id"}, body = {"channel_id", "enabled"} },
    ["discord-bot.update_invite_target_users"] = { method = "PUT", url = "https://discord.com/api/v10/invites/{code}/target-users", path = {"code"}, body = {"target_users_file"} },
    ["discord-bot.update_lobby_message_external_moderation_metadata"] = { method = "PUT", url = "https://discord.com/api/v10/lobbies/{lobby_id}/messages/{message_id}/moderation-metadata", path = {"lobby_id", "message_id"} },
    ["discord-bot.update_message"] = { method = "PATCH", url = "https://discord.com/api/v10/channels/{channel_id}/messages/{message_id}", path = {"channel_id", "message_id"}, body = {"content", "embeds", "flags", "allowed_mentions", "sticker_ids", "components", "attachments"} },
    ["discord-bot.update_my_application"] = { method = "PATCH", url = "https://discord.com/api/v10/applications/@me", body = {"description", "icon", "cover_image", "team_id", "flags", "interactions_endpoint_url", "explicit_content_filter", "max_participants", "type", "tags", "custom_install_url", "install_params", "role_connections_verification_url", "integration_types_config", "event_webhooks_status", "event_webhooks_url", "event_webhooks_types"} },
    ["discord-bot.update_my_guild_member"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/members/@me", path = {"guild_id"}, body = {"nick", "avatar", "bio", "banner"} },
    ["discord-bot.update_my_user"] = { method = "PATCH", url = "https://discord.com/api/v10/users/@me", body = {"username", "avatar", "banner"} },
    ["discord-bot.update_original_webhook_message"] = { method = "PATCH", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}/messages/@original", path = {"webhook_id", "webhook_token"}, query = {"thread_id", "with_components"}, body = {"content", "embeds", "allowed_mentions", "components", "attachments", "poll", "flags"} },
    ["discord-bot.update_self_voice_state"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/voice-states/@me", path = {"guild_id"}, body = {"request_to_speak_timestamp", "suppress", "channel_id"} },
    ["discord-bot.update_stage_instance"] = { method = "PATCH", url = "https://discord.com/api/v10/stage-instances/{channel_id}", path = {"channel_id"}, body = {"topic", "privacy_level"} },
    ["discord-bot.update_user_message_external_moderation_metadata"] = { method = "PUT", url = "https://discord.com/api/v10/partner-sdk/dms/{user_id_1}/{user_id_2}/messages/{message_id}/moderation-metadata", path = {"user_id_1", "user_id_2", "message_id"} },
    ["discord-bot.update_voice_channel_status"] = { method = "PUT", url = "https://discord.com/api/v10/channels/{channel_id}/voice-status", path = {"channel_id"}, body = {"status"} },
    ["discord-bot.update_voice_state"] = { method = "PATCH", url = "https://discord.com/api/v10/guilds/{guild_id}/voice-states/{user_id}", path = {"guild_id", "user_id"}, body = {"suppress", "channel_id"} },
    ["discord-bot.update_webhook"] = { method = "PATCH", url = "https://discord.com/api/v10/webhooks/{webhook_id}", path = {"webhook_id"}, body = {"name", "avatar", "channel_id"} },
    ["discord-bot.update_webhook_by_token"] = { method = "PATCH", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}", path = {"webhook_id", "webhook_token"}, body = {"name", "avatar"} },
    ["discord-bot.update_webhook_message"] = { method = "PATCH", url = "https://discord.com/api/v10/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}", path = {"webhook_id", "webhook_token", "message_id"}, query = {"thread_id", "with_components"}, body = {"content", "embeds", "allowed_mentions", "components", "attachments", "poll", "flags"} },
    ["discord-bot.upload_application_attachment"] = { method = "POST", url = "https://discord.com/api/v10/applications/{application_id}/attachment", path = {"application_id"}, body = {"file"} },
  },
}
