-- La Growth Machine — every call this API accepts, as data.
--
-- GENERATED from https://developers.lagrowthmachine.com/openapi.yaml
-- Published on the vendor's own documentation site (https://developers.lagrowthmachine.com).
-- 54 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "lagrowthmachine",
  name = "La Growth Machine",
  base = "https://apiv2.lagrowthmachine.com",
  docs = "https://nango.dev/docs/integrations/all/lagrowthmachine",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "LAGROWTHMACHINE_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["lagrowthmachine.add_campaign_step_message"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/steps/{stepId}/message", path = {"campaignId", "stepId"}, body = {"newHtml", "subjectNewHtml"} },
    ["lagrowthmachine.archive_conversation"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/inbox/conversations/archive", body = {"conversationId", "leadId", "email", "linkedinUrl", "identityId", "campaignId", "campaignName"} },
    ["lagrowthmachine.complete_call_manual_task"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/manualtasks/call/complete", body = {"manualTaskId", "callStatus", "tag"} },
    ["lagrowthmachine.complete_message_manual_task"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/manualtasks/message/complete", body = {"manualTaskId", "message", "subject", "cc", "bcc", "attachments"} },
    ["lagrowthmachine.create_audience"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/audiences/create", body = {"name"} },
    ["lagrowthmachine.create_audience_from_linkedin_url"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/audiences", body = {"audience", "linkedinUrl", "identityId", "linkedinPostCategory", "excludeContactedLeads", "autoImport"} },
    ["lagrowthmachine.create_inbox_event_webhook"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/inboxWebhooks", body = {"url", "name", "description", "campaigns"} },
    ["lagrowthmachine.create_or_update_alead"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/leads", body = {"audience", "leadId", "firstname", "lastname", "gender", "bio", "note", "companyName", "companyUrl", "jobTitle", "profilePicture", "linkedinUrl", "twitter", "proEmail", "persoEmail", "industry", "phone", "crm_id", "location", "relationsCount", "excludeContactedLeads", "enrichData", "enrichStatus"} },
    ["lagrowthmachine.delete_identity_preference"] = { method = "DELETE", url = "https://apiv2.lagrowthmachine.com/flow/identities/{identityId}/preferences/{preferenceId}", path = {"identityId", "preferenceId"} },
    ["lagrowthmachine.delete_inbox_webhooks"] = { method = "DELETE", url = "https://apiv2.lagrowthmachine.com/flow/inboxWebhooks/{webhookId}", path = {"webhookId"} },
    ["lagrowthmachine.duplicate_accessible_campaign"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/duplicate/accessible/{code}", path = {"code"} },
    ["lagrowthmachine.duplicate_campaign"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/duplicate", path = {"campaignId"} },
    ["lagrowthmachine.edit_campaign_message"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/messages/{templateId}", path = {"campaignId", "templateId"}, body = {"newHtml", "subjectNewHtml"} },
    ["lagrowthmachine.edit_inbox_conversation_note"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/inbox/conversations/note", body = {"conversationId", "leadId", "email", "linkedinUrl", "identityId", "campaignId", "campaignName", "note", "mode"} },
    ["lagrowthmachine.enrich_lead"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/leads/enrich", body = {"leadId", "linkedinUrl", "firstname", "lastname", "companyName", "companyUrl", "enrichType", "mode", "webhookUrl", "source"} },
    ["lagrowthmachine.enrich_linkedin_post"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/posts/enrich", body = {"postUrl"} },
    ["lagrowthmachine.get_audience_detail"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/audiences/{audienceId}/detail", path = {"audienceId"} },
    ["lagrowthmachine.get_audience_leads"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/audiences/{audienceId}/leads", path = {"audienceId"}, query = {"skip", "limit"} },
    ["lagrowthmachine.get_campaign"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}", path = {"campaignId"} },
    ["lagrowthmachine.get_campaign_by_access_code"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/accessible/{code}", path = {"code"} },
    ["lagrowthmachine.get_campaign_leads_stats"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/statsleads", path = {"campaignId"}, query = {"getLeadsAfter", "getLeadsBefore"} },
    ["lagrowthmachine.get_campaign_messages"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/messages", path = {"campaignId"} },
    ["lagrowthmachine.get_campaign_stats"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/stats", path = {"campaignId"} },
    ["lagrowthmachine.get_campaign_steps"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/steps", path = {"campaignId"} },
    ["lagrowthmachine.get_campaigns"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/campaigns", query = {"limit", "skip", "status", "search"} },
    ["lagrowthmachine.get_conversation_messages"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/conversations/{conversationId}/messages", path = {"conversationId"}, query = {"page"} },
    ["lagrowthmachine.get_credits"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/credits" },
    ["lagrowthmachine.get_enrich_result"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/leads/enrich/{enrichRequestId}", path = {"enrichRequestId"} },
    ["lagrowthmachine.get_identity_preferences"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/identities/{identityId}/preferences", path = {"identityId"}, query = {"category"} },
    ["lagrowthmachine.get_lead_conversations"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/leads/{leadId}/conversations", path = {"leadId"}, query = {"identityId"} },
    ["lagrowthmachine.get_lead_logs"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/leads/{leadId}/logs", path = {"leadId"}, query = {"identityId", "skip", "limit"} },
    ["lagrowthmachine.get_me"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/me" },
    ["lagrowthmachine.get_public_campaigns"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/public", query = {"type"} },
    ["lagrowthmachine.list_audiences"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/audiences" },
    ["lagrowthmachine.list_identities"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/identities" },
    ["lagrowthmachine.list_inbox_webhooks"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/inboxWebhooks" },
    ["lagrowthmachine.list_members"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/members" },
    ["lagrowthmachine.list_workspaces"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/workspaces", header = {"X-LGM-Workspace"} },
    ["lagrowthmachine.post_website_visitor_webhook"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/leads/visitors/{provider}/{audienceId}", path = {"provider", "audienceId"}, body = {"LinkedIn URL", "First Name", "Last Name", "Title", "Company Name", "Business Email", "Website", "Industry", "Employee Count", "Estimate Revenue", "City", "State", "Zipcode", "Country", "Seen At", "Referrer", "Captured URL", "Tags", "Session Identification Confidence", "Pages Viewed", "contact", "segment"} },
    ["lagrowthmachine.remove_lead_from_audiences"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/leads/removefromaudience", body = {"audience", "crm_id", "firstname", "lastname", "persoEmail", "proEmail", "linkedinUrl", "twitter", "companyName", "companyUrl"} },
    ["lagrowthmachine.save_identity_preference"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/identities/{identityId}/preferences", path = {"identityId"}, body = {"category", "value", "channel"} },
    ["lagrowthmachine.search_conversations"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/conversations/search", query = {"q", "identityIds", "leadIds", "audienceIds", "campaignIds", "status", "lastMessageStatus", "lastMessageType", "lastMessageAtFrom", "lastMessageAtTo", "callCompletedAtFrom", "callCompletedAtTo", "leadReplied", "unsubscribed", "favourite", "read", "perseverance", "limit", "searchAfter", "sortField", "sortDirection"} },
    ["lagrowthmachine.search_crm"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/crm/search", body = {"email", "proEmail", "persoEmail", "firstname", "lastname", "companyName", "linkedinUrl", "linkedinLongPublicId", "hubspotId", "pipedriveId"} },
    ["lagrowthmachine.search_lead"] = { method = "GET", url = "https://apiv2.lagrowthmachine.com/flow/leads/search", query = {"leadId", "crmId", "firstname", "lastname", "companyName", "companyUrl", "linkedinUrl", "linkedinId", "linkedinPublicId", "linkedinLongPublicId", "email"} },
    ["lagrowthmachine.send_alinkedin_message_to_alead"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/inbox/linkedin", body = {"identityId", "memberId", "leadId", "linkedinUrl", "message", "audioUrl", "attachments", "source"} },
    ["lagrowthmachine.send_an_email_message_to_alead"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/inbox/email", body = {"message", "identityId", "leadId", "leadEmail", "replyInLastThread", "replyToMessageId", "subject", "cc", "bcc", "source"} },
    ["lagrowthmachine.share_campaign_by_code"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/share-by-code", path = {"campaignId"} },
    ["lagrowthmachine.snooze_conversation"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/inbox/conversations/snooze", body = {"conversationId", "leadId", "email", "linkedinUrl", "identityId", "campaignId", "campaignName", "snoozeUntil"} },
    ["lagrowthmachine.stop_sharing_campaign_by_code"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/stop-sharing-by-code", path = {"campaignId"} },
    ["lagrowthmachine.unarchive_conversation"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/inbox/conversations/unarchive", body = {"conversationId", "leadId", "email", "linkedinUrl", "identityId", "campaignId", "campaignName"} },
    ["lagrowthmachine.unsnooze_conversation"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/inbox/conversations/unsnooze", body = {"conversationId", "leadId", "email", "linkedinUrl", "identityId", "campaignId", "campaignName"} },
    ["lagrowthmachine.update_campaign"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/settings", path = {"campaignId"}, body = {"name", "audienceId", "enrich", "autoRescheduleOutOfOffice", "hubspot", "pipedrive", "skipAlreadyContacted", "ignoreEmojiOnlyReply"} },
    ["lagrowthmachine.update_campaign_status"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/campaigns/{campaignId}/status", path = {"campaignId"}, body = {"status"} },
    ["lagrowthmachine.update_lead_status"] = { method = "POST", url = "https://apiv2.lagrowthmachine.com/flow/leads/status", body = {"campaign", "status", "leadId", "crm_id", "firstname", "lastname", "persoEmail", "proEmail", "linkedinUrl", "twitter", "companyName", "companyUrl", "memberEmail", "from"} },
  },
}
