-- Kintone — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/kintone/openapi-spec/main/openapi.json
-- Published by kintone, the vendor's own GitHub organisation.
-- 204 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "kintone",
  name = "Kintone",
  base = "https://{subdomain}.kintone.com",
  docs = "https://nango.dev/docs/integrations/all/kintone",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "KINTONE_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = { ["subdomain"] = "KINTONE_SUBDOMAIN" },
  headers = {},
  operations = {
    ["kintone.delete_guests"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/v1/guests.json", body = {"guests"} },
    ["kintone.delete_guests_for_guest_space"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/guests.json", path = {"guestSpaceId"}, body = {"guests"} },
    ["kintone.delete_preview_app_form_fields"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/v1/preview/app/form/fields.json", body = {"app", "fields", "revision"} },
    ["kintone.delete_preview_app_form_fields_for_guest_space"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/form/fields.json", path = {"guestSpaceId"}, body = {"app", "fields", "revision"} },
    ["kintone.delete_record_comment"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/v1/record/comment.json", body = {"app", "record", "comment"} },
    ["kintone.delete_record_comment_for_guest_space"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/record/comment.json", path = {"guestSpaceId"}, body = {"app", "record", "comment"} },
    ["kintone.delete_records"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/v1/records.json", body = {"app", "ids", "revisions"} },
    ["kintone.delete_records_cursor"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/v1/records/cursor.json", body = {"id"} },
    ["kintone.delete_records_cursor_for_guest_space"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/records/cursor.json", path = {"guestSpaceId"}, body = {"id"} },
    ["kintone.delete_records_for_guest_space"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/records.json", path = {"guestSpaceId"}, body = {"app", "ids", "revisions"} },
    ["kintone.delete_space"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/v1/space.json", body = {"id"} },
    ["kintone.delete_space_for_guest_space"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/space.json", path = {"guestSpaceId"}, body = {"id"} },
    ["kintone.deploy_app"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/preview/app/deploy.json", body = {"revert", "apps"} },
    ["kintone.deploy_app_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/deploy.json", path = {"guestSpaceId"}, body = {"revert", "apps"} },
    ["kintone.download_file"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/file.json", query = {"fileKey"} },
    ["kintone.download_file_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/file.json", path = {"guestSpaceId"}, query = {"fileKey"} },
    ["kintone.get_app"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app.json", query = {"id"} },
    ["kintone.get_app_acl"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/acl.json", query = {"app"} },
    ["kintone.get_app_acl_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/acl.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_app_actions"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/actions.json", query = {"app", "lang"} },
    ["kintone.get_app_actions_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/actions.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_app_admin_notes"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/adminNotes.json", query = {"app"} },
    ["kintone.get_app_admin_notes_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/adminNotes.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_app_customize"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/customize.json", query = {"app"} },
    ["kintone.get_app_customize_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/customize.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_app_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app.json", path = {"guestSpaceId"}, query = {"id"} },
    ["kintone.get_app_form_fields"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/form/fields.json", query = {"app", "lang"} },
    ["kintone.get_app_form_fields_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/form/fields.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_app_form_layout"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/form/layout.json", query = {"app"} },
    ["kintone.get_app_form_layout_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/form/layout.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_app_notifications_general"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/notifications/general.json", query = {"app"} },
    ["kintone.get_app_notifications_general_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/notifications/general.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_app_notifications_per_record"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/notifications/perRecord.json", query = {"app", "lang"} },
    ["kintone.get_app_notifications_per_record_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/notifications/perRecord.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_app_notifications_reminder"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/notifications/reminder.json", query = {"app", "lang"} },
    ["kintone.get_app_notifications_reminder_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/notifications/reminder.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_app_plugins"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/plugins.json", query = {"app", "lang"} },
    ["kintone.get_app_plugins_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/plugins.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_app_reports"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/reports.json", query = {"app", "lang"} },
    ["kintone.get_app_reports_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/reports.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_app_settings"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/settings.json", query = {"app", "lang"} },
    ["kintone.get_app_settings_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/settings.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_app_status"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/status.json", query = {"app", "lang"} },
    ["kintone.get_app_status_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/status.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_app_views"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/app/views.json", query = {"app", "lang"} },
    ["kintone.get_app_views_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/views.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_apps"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/apps.json", query = {"codes", "offset", "name", "limit", "ids", "spaceIds"} },
    ["kintone.get_apps_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/apps.json", path = {"guestSpaceId"}, query = {"codes", "offset", "name", "limit", "ids", "spaceIds"} },
    ["kintone.get_apps_statistics"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/apps/statistics.json", query = {"offset", "limit"} },
    ["kintone.get_apps_statistics_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/apps/statistics.json", path = {"guestSpaceId"}, query = {"offset", "limit"} },
    ["kintone.get_field_acl"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/field/acl.json", query = {"app"} },
    ["kintone.get_field_acl_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/field/acl.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_form"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/form.json", query = {"app"} },
    ["kintone.get_form_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/form.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_plugin_apps"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/plugin/apps.json", query = {"offset", "limit", "id"} },
    ["kintone.get_plugin_apps_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/plugin/apps.json", path = {"guestSpaceId"}, query = {"offset", "limit", "id"} },
    ["kintone.get_plugins"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/plugins.json", query = {"offset", "limit", "ids"} },
    ["kintone.get_plugins_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/plugins.json", path = {"guestSpaceId"}, query = {"offset", "limit", "ids"} },
    ["kintone.get_plugins_required"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/plugins/required.json", query = {"offset", "limit"} },
    ["kintone.get_plugins_required_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/plugins/required.json", path = {"guestSpaceId"}, query = {"offset", "limit"} },
    ["kintone.get_preview_app_acl"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/acl.json", query = {"app"} },
    ["kintone.get_preview_app_acl_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/acl.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_preview_app_actions"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/actions.json", query = {"app", "lang"} },
    ["kintone.get_preview_app_actions_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/actions.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_preview_app_admin_notes"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/adminNotes.json", query = {"app"} },
    ["kintone.get_preview_app_admin_notes_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/adminNotes.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_preview_app_customize"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/customize.json", query = {"app"} },
    ["kintone.get_preview_app_customize_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/customize.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_preview_app_deploy"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/deploy.json", query = {"apps"} },
    ["kintone.get_preview_app_deploy_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/deploy.json", path = {"guestSpaceId"}, query = {"apps"} },
    ["kintone.get_preview_app_form_fields"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/form/fields.json", query = {"app", "lang"} },
    ["kintone.get_preview_app_form_fields_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/form/fields.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_preview_app_form_layout"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/form/layout.json", query = {"app"} },
    ["kintone.get_preview_app_form_layout_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/form/layout.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_preview_app_notifications_general"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/notifications/general.json", query = {"app"} },
    ["kintone.get_preview_app_notifications_general_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/notifications/general.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_preview_app_notifications_per_record"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/notifications/perRecord.json", query = {"app", "lang"} },
    ["kintone.get_preview_app_notifications_per_record_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/notifications/perRecord.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_preview_app_notifications_reminder"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/notifications/reminder.json", query = {"app", "lang"} },
    ["kintone.get_preview_app_notifications_reminder_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/notifications/reminder.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_preview_app_plugins"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/plugins.json", query = {"app", "lang"} },
    ["kintone.get_preview_app_plugins_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/plugins.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_preview_app_reports"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/reports.json", query = {"app", "lang"} },
    ["kintone.get_preview_app_reports_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/reports.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_preview_app_settings"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/settings.json", query = {"app", "lang"} },
    ["kintone.get_preview_app_settings_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/settings.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_preview_app_status"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/status.json", query = {"app", "lang"} },
    ["kintone.get_preview_app_status_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/status.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_preview_app_views"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/app/views.json", query = {"app", "lang"} },
    ["kintone.get_preview_app_views_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/views.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_preview_field_acl"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/field/acl.json", query = {"app"} },
    ["kintone.get_preview_field_acl_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/field/acl.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_preview_form"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/form.json", query = {"app"} },
    ["kintone.get_preview_form_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/form.json", path = {"guestSpaceId"}, query = {"app"} },
    ["kintone.get_preview_record_acl"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/preview/record/acl.json", query = {"app", "lang"} },
    ["kintone.get_preview_record_acl_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/record/acl.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_record"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/record.json", query = {"app", "id"} },
    ["kintone.get_record_acl"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/record/acl.json", query = {"app", "lang"} },
    ["kintone.get_record_acl_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/record/acl.json", path = {"guestSpaceId"}, query = {"app", "lang"} },
    ["kintone.get_record_comments"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/record/comments.json", query = {"app", "offset", "record", "limit", "order"} },
    ["kintone.get_record_comments_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/record/comments.json", path = {"guestSpaceId"}, query = {"app", "offset", "record", "limit", "order"} },
    ["kintone.get_record_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/record.json", path = {"guestSpaceId"}, query = {"app", "id"} },
    ["kintone.get_records"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/records.json", query = {"app", "query", "fields", "totalCount"} },
    ["kintone.get_records_acl_evaluate"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/records/acl/evaluate.json", query = {"app", "ids"} },
    ["kintone.get_records_acl_evaluate_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/records/acl/evaluate.json", path = {"guestSpaceId"}, query = {"app", "ids"} },
    ["kintone.get_records_cursor"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/records/cursor.json", query = {"id"} },
    ["kintone.get_records_cursor_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/records/cursor.json", path = {"guestSpaceId"}, query = {"id"} },
    ["kintone.get_records_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/records.json", path = {"guestSpaceId"}, query = {"app", "query", "fields", "totalCount"} },
    ["kintone.get_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/space.json", query = {"id"} },
    ["kintone.get_space_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/space.json", path = {"guestSpaceId"}, query = {"id"} },
    ["kintone.get_space_members"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/space/members.json", query = {"id"} },
    ["kintone.get_space_members_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/space/members.json", path = {"guestSpaceId"}, query = {"id"} },
    ["kintone.get_spaces_statistics"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/v1/spaces/statistics.json", query = {"offset", "limit"} },
    ["kintone.get_spaces_statistics_for_guest_space"] = { method = "GET", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/spaces/statistics.json", path = {"guestSpaceId"}, query = {"offset", "limit"} },
    ["kintone.install_plugin"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/plugin.json", body = {"fileKey"} },
    ["kintone.install_plugin_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/plugin.json", path = {"guestSpaceId"}, body = {"fileKey"} },
    ["kintone.post_app_move"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/app/move.json", body = {"app", "space"} },
    ["kintone.post_app_move_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/move.json", path = {"guestSpaceId"}, body = {"app", "space"} },
    ["kintone.post_bulk_request"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/bulkRequest.json", body = {"requests"} },
    ["kintone.post_bulk_request_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/bulkRequest.json", path = {"guestSpaceId"}, body = {"requests"} },
    ["kintone.post_guests"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/guests.json", body = {"guests"} },
    ["kintone.post_guests_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/guests.json", path = {"guestSpaceId"}, body = {"guests"} },
    ["kintone.post_preview_app"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/preview/app.json", body = {"name", "thread", "space"} },
    ["kintone.post_preview_app_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app.json", path = {"guestSpaceId"}, body = {"name", "thread", "space"} },
    ["kintone.post_preview_app_form_fields"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/preview/app/form/fields.json", body = {"app", "properties", "revision"} },
    ["kintone.post_preview_app_form_fields_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/form/fields.json", path = {"guestSpaceId"}, body = {"app", "properties", "revision"} },
    ["kintone.post_preview_app_plugins"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/preview/app/plugins.json", body = {"app", "ids", "revision"} },
    ["kintone.post_preview_app_plugins_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/plugins.json", path = {"guestSpaceId"}, body = {"app", "ids", "revision"} },
    ["kintone.post_record"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/record.json", body = {"app", "record"} },
    ["kintone.post_record_async_token"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/record/async/token.json", body = {"app"} },
    ["kintone.post_record_comment"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/record/comment.json", body = {"app", "record", "comment"} },
    ["kintone.post_record_comment_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/record/comment.json", path = {"guestSpaceId"}, body = {"app", "record", "comment"} },
    ["kintone.post_record_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/record.json", path = {"guestSpaceId"}, body = {"app", "record"} },
    ["kintone.post_records"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/records.json", body = {"app", "records"} },
    ["kintone.post_records_cursor"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/records/cursor.json", body = {"app", "size", "query", "fields"} },
    ["kintone.post_records_cursor_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/records/cursor.json", path = {"guestSpaceId"}, body = {"app", "size", "query", "fields"} },
    ["kintone.post_records_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/records.json", path = {"guestSpaceId"}, body = {"app", "records"} },
    ["kintone.post_space_thread"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/space/thread.json", body = {"name", "space"} },
    ["kintone.post_space_thread_comment"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/space/thread/comment.json", body = {"comment", "thread", "space"} },
    ["kintone.post_space_thread_comment_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/space/thread/comment.json", path = {"guestSpaceId"}, body = {"comment", "thread", "space"} },
    ["kintone.post_space_thread_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/space/thread.json", path = {"guestSpaceId"}, body = {"name", "space"} },
    ["kintone.post_template_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/template/space.json", body = {"fixedMember", "isGuest", "members", "name", "id", "isPrivate"} },
    ["kintone.post_template_space_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/template/space.json", path = {"guestSpaceId"}, body = {"fixedMember", "isGuest", "members", "name", "id", "isPrivate"} },
    ["kintone.put_app_acl"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/app/acl.json", body = {"app", "rights", "revision"} },
    ["kintone.put_app_acl_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/app/acl.json", path = {"guestSpaceId"}, body = {"app", "rights", "revision"} },
    ["kintone.put_field_acl"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/field/acl.json", body = {"app", "rights", "id", "revision"} },
    ["kintone.put_field_acl_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/field/acl.json", path = {"guestSpaceId"}, body = {"app", "rights", "id", "revision"} },
    ["kintone.put_plugin"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/plugin.json", body = {"fileKey", "id"} },
    ["kintone.put_plugin_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/plugin.json", path = {"guestSpaceId"}, body = {"fileKey", "id"} },
    ["kintone.put_preview_app_acl"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/acl.json", body = {"app", "rights", "revision"} },
    ["kintone.put_preview_app_acl_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/acl.json", path = {"guestSpaceId"}, body = {"app", "rights", "revision"} },
    ["kintone.put_preview_app_actions"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/actions.json", body = {"app", "actions", "revision"} },
    ["kintone.put_preview_app_actions_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/actions.json", path = {"guestSpaceId"}, body = {"app", "actions", "revision"} },
    ["kintone.put_preview_app_admin_notes"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/adminNotes.json", body = {"app", "content", "revision", "includeInTemplateAndDuplicates"} },
    ["kintone.put_preview_app_admin_notes_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/adminNotes.json", path = {"guestSpaceId"}, body = {"app", "content", "revision", "includeInTemplateAndDuplicates"} },
    ["kintone.put_preview_app_customize"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/customize.json", body = {"app", "desktop", "scope", "mobile", "revision"} },
    ["kintone.put_preview_app_customize_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/customize.json", path = {"guestSpaceId"}, body = {"app", "desktop", "scope", "mobile", "revision"} },
    ["kintone.put_preview_app_form_fields"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/form/fields.json", body = {"app", "properties", "revision"} },
    ["kintone.put_preview_app_form_fields_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/form/fields.json", path = {"guestSpaceId"}, body = {"app", "properties", "revision"} },
    ["kintone.put_preview_app_form_layout"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/form/layout.json", body = {"app", "layout", "revision"} },
    ["kintone.put_preview_app_form_layout_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/form/layout.json", path = {"guestSpaceId"}, body = {"app", "layout", "revision"} },
    ["kintone.put_preview_app_notifications_general"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/notifications/general.json", body = {"app", "notifyToCommenter", "notifications", "revision"} },
    ["kintone.put_preview_app_notifications_general_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/notifications/general.json", path = {"guestSpaceId"}, body = {"app", "notifyToCommenter", "notifications", "revision"} },
    ["kintone.put_preview_app_notifications_per_record"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/notifications/perRecord.json", body = {"app", "notifications", "revision"} },
    ["kintone.put_preview_app_notifications_per_record_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/notifications/perRecord.json", path = {"guestSpaceId"}, body = {"app", "notifications", "revision"} },
    ["kintone.put_preview_app_notifications_reminder"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/notifications/reminder.json", body = {"app", "timezone", "notifications", "revision"} },
    ["kintone.put_preview_app_notifications_reminder_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/notifications/reminder.json", path = {"guestSpaceId"}, body = {"app", "timezone", "notifications", "revision"} },
    ["kintone.put_preview_app_reports"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/reports.json", body = {"app", "reports", "revision"} },
    ["kintone.put_preview_app_reports_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/reports.json", path = {"guestSpaceId"}, body = {"app", "reports", "revision"} },
    ["kintone.put_preview_app_settings"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/settings.json", body = {"app", "enableComments", "titleField", "icon", "description", "enableThumbnails", "enableDuplicateRecord", "revision", "enableInlineRecordEditing", "enableBulkDeletion", "name", "theme", "numberPrecision", "firstMonthOfFiscalYear"} },
    ["kintone.put_preview_app_settings_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/settings.json", path = {"guestSpaceId"}, body = {"app", "enableComments", "titleField", "icon", "description", "enableThumbnails", "enableDuplicateRecord", "revision", "enableInlineRecordEditing", "enableBulkDeletion", "name", "theme", "numberPrecision", "firstMonthOfFiscalYear"} },
    ["kintone.put_preview_app_status"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/status.json", body = {"app", "enable", "actions", "revision", "states"} },
    ["kintone.put_preview_app_status_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/status.json", path = {"guestSpaceId"}, body = {"app", "enable", "actions", "revision", "states"} },
    ["kintone.put_preview_app_views"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/app/views.json", body = {"app", "views", "revision"} },
    ["kintone.put_preview_app_views_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/app/views.json", path = {"guestSpaceId"}, body = {"app", "views", "revision"} },
    ["kintone.put_preview_field_acl"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/field/acl.json", body = {"app", "rights", "id", "revision"} },
    ["kintone.put_preview_field_acl_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/field/acl.json", path = {"guestSpaceId"}, body = {"app", "rights", "id", "revision"} },
    ["kintone.put_preview_record_acl"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/preview/record/acl.json", body = {"app", "rights", "id", "revision"} },
    ["kintone.put_preview_record_acl_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/preview/record/acl.json", path = {"guestSpaceId"}, body = {"app", "rights", "id", "revision"} },
    ["kintone.put_record"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/record.json", body = {"app", "updateKey", "record", "id", "revision"} },
    ["kintone.put_record_acl"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/record/acl.json", body = {"app", "rights", "id", "revision"} },
    ["kintone.put_record_acl_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/record/acl.json", path = {"guestSpaceId"}, body = {"app", "rights", "id", "revision"} },
    ["kintone.put_record_assignees"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/record/assignees.json", body = {"app", "assignees", "id", "revision"} },
    ["kintone.put_record_assignees_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/record/assignees.json", path = {"guestSpaceId"}, body = {"app", "assignees", "id", "revision"} },
    ["kintone.put_record_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/record.json", path = {"guestSpaceId"}, body = {"app", "updateKey", "record", "id", "revision"} },
    ["kintone.put_record_status"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/record/status.json", body = {"app", "action", "id", "assignee", "revision"} },
    ["kintone.put_record_status_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/record/status.json", path = {"guestSpaceId"}, body = {"app", "action", "id", "assignee", "revision"} },
    ["kintone.put_records"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/records.json", body = {"app", "records", "upsert"} },
    ["kintone.put_records_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/records.json", path = {"guestSpaceId"}, body = {"app", "records", "upsert"} },
    ["kintone.put_records_status"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/records/status.json", body = {"app", "records"} },
    ["kintone.put_records_status_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/records/status.json", path = {"guestSpaceId"}, body = {"app", "records"} },
    ["kintone.put_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/space.json", body = {"fixedMember", "permissions", "name", "useMultiThread", "showMemberList", "showRelatedLinkList", "id", "isPrivate", "showAnnouncement", "showThreadList", "showAppList"} },
    ["kintone.put_space_body"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/space/body.json", body = {"id", "body"} },
    ["kintone.put_space_body_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/space/body.json", path = {"guestSpaceId"}, body = {"id", "body"} },
    ["kintone.put_space_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/space.json", path = {"guestSpaceId"}, body = {"fixedMember", "permissions", "name", "useMultiThread", "showMemberList", "showRelatedLinkList", "id", "isPrivate", "showAnnouncement", "showThreadList", "showAppList"} },
    ["kintone.put_space_guests_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/space/guests.json", path = {"guestSpaceId"}, body = {"guests", "id"} },
    ["kintone.put_space_members"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/space/members.json", body = {"members", "id"} },
    ["kintone.put_space_members_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/space/members.json", path = {"guestSpaceId"}, body = {"members", "id"} },
    ["kintone.put_space_thread"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/v1/space/thread.json", body = {"name", "id", "body"} },
    ["kintone.put_space_thread_for_guest_space"] = { method = "PUT", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/space/thread.json", path = {"guestSpaceId"}, body = {"name", "id", "body"} },
    ["kintone.uninstall_plugin"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/v1/plugin.json", body = {"id"} },
    ["kintone.uninstall_plugin_for_guest_space"] = { method = "DELETE", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/plugin.json", path = {"guestSpaceId"}, body = {"id"} },
    ["kintone.upload_file"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/v1/file.json", body = {"file"} },
    ["kintone.upload_file_for_guest_space"] = { method = "POST", url = "https://{subdomain}.kintone.com/k/guest/{guestSpaceId}/v1/file.json", path = {"guestSpaceId"}, body = {"file"} },
  },
}
