-- Clarify — every call this API accepts, as data.
--
-- GENERATED from https://clarify.ai/openapi.json
-- Published on the vendor's own documentation site (https://clarify.ai).
-- 90 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "clarify",
  name = "Clarify",
  base = "https://api.clarify.ai",
  docs = "https://nango.dev/docs/api-integrations/clarify",
  auth = {
    kind = "key",
    header = "authorization",
    format = "api-key {token}",
    env = "CLARIFY_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["clarify.add_record_attachment"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/attachments", path = {"workspace", "object", "id"}, query = {"silent"}, body = {"name", "attachmentId"} },
    ["clarify.confirm_media_upload"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/meetings/{meetingId}/recordings/media/{recordingId}", path = {"workspace", "meetingId", "recordingId"}, query = {"silent"} },
    ["clarify.create_api_key"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/api-keys", path = {"workspace"}, query = {"silent"}, body = {"data"} },
    ["clarify.create_bulk_records"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/bulk", path = {"workspace", "object"}, query = {"silent"}, body = {"data", "match_on"} },
    ["clarify.create_comment"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/comments", path = {"workspace"}, query = {"silent"}, body = {"_id", "message", "owner_id", "entity", "_event_id"} },
    ["clarify.create_custom_object"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas/objects", path = {"workspace"}, query = {"silent"}, body = {"name", "plural", "description", "icon", "backgroundColor", "properties"} },
    ["clarify.create_grant"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/access", path = {"workspace", "object", "id"}, query = {"silent"}, body = {"data"} },
    ["clarify.create_grants_bulk"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/access/bulk", path = {"workspace", "object", "id"}, query = {"silent"}, body = {"data"} },
    ["clarify.create_invitation"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/invitations", path = {"workspace"}, query = {"silent"}, body = {"data"} },
    ["clarify.create_list"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/lists", path = {"workspace", "object"}, query = {"silent"}, body = {"title", "emoji", "description", "layout", "options", "query", "rank", "type", "state"} },
    ["clarify.create_record"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records", path = {"workspace", "object"}, query = {"silent"}, body = {"data", "match_on"} },
    ["clarify.create_resource"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/resources", path = {"workspace", "object"}, query = {"silent"}, body = {"data"} },
    ["clarify.create_schema_properties"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas/{entity}/properties", path = {"workspace", "entity"}, query = {"silent"}, body = {"data"} },
    ["clarify.create_schema_relationship_properties"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas/{entity}/relationships", path = {"workspace", "entity"}, query = {"silent"}, body = {"data"} },
    ["clarify.create_workflow"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/workflows", path = {"workspace"}, query = {"silent"}, body = {"data"} },
    ["clarify.create_workspace"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces", query = {"silent"}, body = {"data"} },
    ["clarify.delete_api_key"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/api-keys/{id}", path = {"workspace", "id"}, query = {"silent"} },
    ["clarify.delete_comment"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/comments/{id}", path = {"workspace", "id"}, query = {"silent"} },
    ["clarify.delete_custom_object"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas/objects/{object}", path = {"workspace", "object"}, query = {"silent"} },
    ["clarify.delete_list"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/lists/{list}", path = {"workspace", "object", "list"}, query = {"silent"} },
    ["clarify.delete_record"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}", path = {"workspace", "object", "id"}, query = {"silent"} },
    ["clarify.delete_record_attachment"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/attachments/{attachmentId}", path = {"workspace", "object", "id", "attachmentId"}, query = {"silent"} },
    ["clarify.delete_record_relationship"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/relationships/{relationship}", path = {"workspace", "object", "id", "relationship"}, query = {"silent"}, body = {"data"} },
    ["clarify.delete_records"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records", path = {"workspace", "object"}, query = {"silent"}, body = {"items"} },
    ["clarify.delete_schema_relationship_property"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas/{entity}/relationships/{fieldName}", path = {"workspace", "entity", "fieldName"}, query = {"silent"} },
    ["clarify.delete_workflow"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/workflows/{id}", path = {"workspace", "id"}, query = {"silent"} },
    ["clarify.delete_workspace_setting"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/settings", path = {"workspace"}, query = {"silent"} },
    ["clarify.disable_recording"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/meetings/{meetingId}/recording", path = {"workspace", "meetingId"}, query = {"silent"} },
    ["clarify.enable_recording"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/meetings/{meetingId}/recording", path = {"workspace", "meetingId"}, query = {"silent"} },
    ["clarify.get_activities"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{record}/activities", path = {"workspace", "object", "record"}, query = {"page", "sortOrder"} },
    ["clarify.get_api_keys"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/api-keys", path = {"workspace"} },
    ["clarify.get_cli_auth_config"] = { method = "GET", url = "https://api.clarify.ai/v1/auth/cli" },
    ["clarify.get_comment"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/comments/{id}", path = {"workspace", "id"} },
    ["clarify.get_current_user"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/users/me", path = {"workspace"} },
    ["clarify.get_deleted_resources"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/deleted-resources", path = {"workspace", "object"}, query = {"page", "filter"} },
    ["clarify.get_grants"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/access", path = {"workspace", "object", "id"} },
    ["clarify.get_invitations"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/invitations", path = {"workspace"} },
    ["clarify.get_layout_by_id"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/layouts/{id}", path = {"workspace", "id"} },
    ["clarify.get_list"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/lists/{list}", path = {"workspace", "object", "list"} },
    ["clarify.get_list_resources"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/lists/{list}/resources", path = {"workspace", "object", "list"}, query = {"page", "sortOrder", "include", "filter"} },
    ["clarify.get_list_rows_csv"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/lists/{list}/rows/csv", path = {"workspace", "object", "list"}, query = {"silent"}, body = {"sql", "search"} },
    ["clarify.get_lists"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/lists", path = {"workspace", "object"}, query = {"page", "sortOrder", "filter", "search"} },
    ["clarify.get_object_access"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/access", path = {"workspace", "object"} },
    ["clarify.get_recipients"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/campaigns/{campaignId}/recipients", path = {"workspace", "campaignId"}, query = {"page", "sortOrder", "filter"} },
    ["clarify.get_record"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}", path = {"workspace", "object", "id"}, query = {"include"} },
    ["clarify.get_record_attachment"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/attachments/{attachmentId}", path = {"workspace", "object", "id", "attachmentId"} },
    ["clarify.get_record_relationships"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/relationships/{relationship}", path = {"workspace", "object", "id", "relationship"}, query = {"page", "sortOrder", "include"} },
    ["clarify.get_recording_artifacts"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/meetings/{meetingId}/recordings/{id}/artifacts", path = {"workspace", "meetingId", "id"}, query = {"silent"} },
    ["clarify.get_resource"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/resources/{id}", path = {"workspace", "object", "id"}, query = {"include"} },
    ["clarify.get_resources"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/resources", path = {"workspace", "object"}, query = {"page", "sortOrder", "include", "filter"} },
    ["clarify.get_schema_activities"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas/{entity}/activities", path = {"workspace", "entity"}, query = {"page", "sortOrder"} },
    ["clarify.get_schemas"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas", path = {"workspace"} },
    ["clarify.get_signed_url_for_record_attachment_upload"] = { method = "PUT", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/attachments", path = {"workspace", "object", "id"}, query = {"silent"}, body = {"name"} },
    ["clarify.get_user"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/users/{userId}", path = {"workspace", "userId"} },
    ["clarify.get_users"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/users", path = {"workspace"}, query = {"page", "sortOrder"} },
    ["clarify.get_workflow"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/workflows/{id}", path = {"workspace", "id"} },
    ["clarify.get_workflows"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/workflows", path = {"workspace"}, query = {"page", "sortOrder", "filter"} },
    ["clarify.get_workspace"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}", path = {"workspace"} },
    ["clarify.get_workspace_lists"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/lists", path = {"workspace"}, query = {"page", "sortOrder", "filter", "search"} },
    ["clarify.give_object_access"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/access", path = {"workspace", "object"}, query = {"silent"}, body = {"data"} },
    ["clarify.init_media_upload"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/meetings/{meetingId}/recordings/media", path = {"workspace", "meetingId"}, query = {"silent"}, body = {"recordingId", "contentType", "transcript"} },
    ["clarify.list_record_attachments"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/attachments", path = {"workspace", "object", "id"}, query = {"page"} },
    ["clarify.list_workspaces"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces" },
    ["clarify.merge_records"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{record}/merges", path = {"workspace", "object", "record"}, query = {"silent"}, body = {"data"} },
    ["clarify.patch_enum_field_values"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas", path = {"workspace"}, query = {"silent"}, body = {"data"} },
    ["clarify.publish_list"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/lists/{list}/publish", path = {"workspace", "object", "list"}, query = {"silent"} },
    ["clarify.read_all_workspace_settings"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/settings", path = {"workspace"} },
    ["clarify.read_workspace_settings"] = { method = "GET", url = "https://api.clarify.ai/v1/workspaces/{workspace}/settings/{key}", path = {"workspace"} },
    ["clarify.remove_user"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/users/{userId}", path = {"workspace", "userId"}, query = {"silent"} },
    ["clarify.resend_invitation"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/invitations/{invitationId}/resend", path = {"workspace", "invitationId"}, query = {"silent"} },
    ["clarify.reset_layout"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/layouts/{id}/reset", path = {"workspace", "id"}, query = {"silent"} },
    ["clarify.revoke_grant"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/access/{grantId}", path = {"workspace", "object", "id", "grantId"}, query = {"silent"} },
    ["clarify.revoke_invitation"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/invitations/{invitationId}", path = {"workspace", "invitationId"}, query = {"silent"} },
    ["clarify.revoke_object_access"] = { method = "DELETE", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/access/{id}", path = {"workspace", "object", "id"}, query = {"silent"} },
    ["clarify.unpublish_list"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/lists/{list}/unpublish", path = {"workspace", "object", "list"}, query = {"silent"} },
    ["clarify.update_comment"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/comments/{id}", path = {"workspace", "id"}, query = {"silent"}, body = {"message"} },
    ["clarify.update_entity_schema"] = { method = "PUT", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas/objects/{object}", path = {"workspace", "object"}, query = {"silent"} },
    ["clarify.update_grant"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/access/{grantId}", path = {"workspace", "object", "id", "grantId"}, query = {"silent"}, body = {"data"} },
    ["clarify.update_layout"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/layouts/{id}", path = {"workspace", "id"}, query = {"silent"}, body = {"data", "meta"} },
    ["clarify.update_list"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/lists/{list}", path = {"workspace", "object", "list"}, query = {"silent"}, body = {"title", "emoji", "description", "layout", "options", "query", "rank"} },
    ["clarify.update_record"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}", path = {"workspace", "object", "id"}, query = {"silent"}, body = {"data", "meta"} },
    ["clarify.update_record_relationship"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records/{id}/relationships/{relationship}", path = {"workspace", "object", "id", "relationship"}, query = {"silent"}, body = {"data"} },
    ["clarify.update_records"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/objects/{object}/records", path = {"workspace", "object"}, query = {"silent"}, body = {"data", "meta"} },
    ["clarify.update_schema_property_order"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas/{entity}/fields-order", path = {"workspace", "entity"}, query = {"silent"}, body = {"data"} },
    ["clarify.update_schema_property_visibility"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/schemas/{entity}/fields-visibility", path = {"workspace", "entity"}, query = {"silent"}, body = {"data"} },
    ["clarify.update_user_role"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/users/{userId}/role", path = {"workspace", "userId"}, query = {"silent"}, body = {"role"} },
    ["clarify.update_workflow"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}/workflows/{id}", path = {"workspace", "id"}, query = {"silent"}, body = {"data", "meta"} },
    ["clarify.update_workspace"] = { method = "PATCH", url = "https://api.clarify.ai/v1/workspaces/{workspace}", path = {"workspace"}, query = {"silent"}, body = {"data"} },
    ["clarify.upload_recording_transcript"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/meetings/{meetingId}/recordings/transcript", path = {"workspace", "meetingId"}, query = {"silent"}, body = {"recordingId", "transcript"} },
    ["clarify.write_workspace_setting"] = { method = "POST", url = "https://api.clarify.ai/v1/workspaces/{workspace}/settings", path = {"workspace"}, query = {"silent"}, body = {"value"} },
  },
}
