-- Gmail — every call this API accepts, as data.
--
-- GENERATED from https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
-- Google's own discovery document
-- 79 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "gmail",
  name = "Gmail",
  base = "https://gmail.googleapis.com",
  docs = "https://developers.google.com/gmail/api/reference/rest",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "GOOGLE_ACCESS_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["gmail.users.drafts.create"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts", path = {"userId"}, body = {"id", "message"} },
    ["gmail.users.drafts.delete"] = { method = "DELETE", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts/{id}", path = {"id", "userId"} },
    ["gmail.users.drafts.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts/{id}", path = {"userId", "id"}, query = {"format"} },
    ["gmail.users.drafts.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts", path = {"userId"}, query = {"pageToken", "maxResults", "q", "includeSpamTrash"} },
    ["gmail.users.drafts.send"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts/send", path = {"userId"}, body = {"id", "message"} },
    ["gmail.users.drafts.update"] = { method = "PUT", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts/{id}", path = {"id", "userId"}, body = {"id", "message"} },
    ["gmail.users.getProfile"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/profile", path = {"userId"} },
    ["gmail.users.history.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/history", path = {"userId"}, query = {"historyTypes", "pageToken", "labelId", "startHistoryId", "maxResults"} },
    ["gmail.users.labels.create"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels", path = {"userId"}, body = {"threadsUnread", "labelListVisibility", "type", "name", "messagesTotal", "messagesUnread", "threadsTotal", "id", "color", "messageListVisibility"} },
    ["gmail.users.labels.delete"] = { method = "DELETE", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels/{id}", path = {"userId", "id"} },
    ["gmail.users.labels.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels/{id}", path = {"userId", "id"} },
    ["gmail.users.labels.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels", path = {"userId"} },
    ["gmail.users.labels.patch"] = { method = "PATCH", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels/{id}", path = {"id", "userId"}, body = {"threadsUnread", "labelListVisibility", "type", "name", "messagesTotal", "messagesUnread", "threadsTotal", "id", "color", "messageListVisibility"} },
    ["gmail.users.labels.update"] = { method = "PUT", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels/{id}", path = {"id", "userId"}, body = {"threadsUnread", "labelListVisibility", "type", "name", "messagesTotal", "messagesUnread", "threadsTotal", "id", "color", "messageListVisibility"} },
    ["gmail.users.messages.attachments.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}", path = {"messageId", "userId", "id"} },
    ["gmail.users.messages.batchDelete"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/batchDelete", path = {"userId"}, body = {"ids"} },
    ["gmail.users.messages.batchModify"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/batchModify", path = {"userId"}, body = {"ids", "removeLabelIds", "addClassificationLabels", "addLabelIds", "removeClassificationLabelIds"} },
    ["gmail.users.messages.delete"] = { method = "DELETE", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{id}", path = {"id", "userId"} },
    ["gmail.users.messages.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{id}", path = {"userId", "id"}, query = {"format", "metadataHeaders"} },
    ["gmail.users.messages.import"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/import", path = {"userId"}, query = {"neverMarkSpam", "processForCalendar", "deleted", "internalDateSource"}, body = {"classificationLabelValues", "internalDate", "payload", "raw", "labelIds", "snippet", "id", "threadId", "historyId", "sizeEstimate"} },
    ["gmail.users.messages.insert"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages", path = {"userId"}, query = {"deleted", "internalDateSource"}, body = {"classificationLabelValues", "internalDate", "payload", "raw", "labelIds", "snippet", "id", "threadId", "historyId", "sizeEstimate"} },
    ["gmail.users.messages.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages", path = {"userId"}, query = {"maxResults", "includeSpamTrash", "pageToken", "labelIds", "q"} },
    ["gmail.users.messages.modify"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{id}/modify", path = {"id", "userId"}, body = {"addLabelIds", "removeClassificationLabelIds", "removeLabelIds", "addClassificationLabels"} },
    ["gmail.users.messages.send"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/send", path = {"userId"}, body = {"classificationLabelValues", "internalDate", "payload", "raw", "labelIds", "snippet", "id", "threadId", "historyId", "sizeEstimate"} },
    ["gmail.users.messages.trash"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{id}/trash", path = {"id", "userId"} },
    ["gmail.users.messages.untrash"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{id}/untrash", path = {"id", "userId"} },
    ["gmail.users.settings.cse.identities.create"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/identities", path = {"userId"}, body = {"primaryKeyPairId", "emailAddress", "signAndEncryptKeyPairs"} },
    ["gmail.users.settings.cse.identities.delete"] = { method = "DELETE", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}", path = {"userId", "cseEmailAddress"} },
    ["gmail.users.settings.cse.identities.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}", path = {"cseEmailAddress", "userId"} },
    ["gmail.users.settings.cse.identities.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/identities", path = {"userId"}, query = {"pageToken", "pageSize"} },
    ["gmail.users.settings.cse.identities.patch"] = { method = "PATCH", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}", path = {"emailAddress", "userId"}, body = {"primaryKeyPairId", "emailAddress", "signAndEncryptKeyPairs"} },
    ["gmail.users.settings.cse.keypairs.create"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/keypairs", path = {"userId"}, query = {"chainValidation"}, body = {"privateKeyMetadata", "subjectEmailAddresses", "enablementState", "pkcs7", "keyPairId", "disableTime", "pem"} },
    ["gmail.users.settings.cse.keypairs.disable"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable", path = {"keyPairId", "userId"} },
    ["gmail.users.settings.cse.keypairs.enable"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable", path = {"keyPairId", "userId"} },
    ["gmail.users.settings.cse.keypairs.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}", path = {"userId", "keyPairId"} },
    ["gmail.users.settings.cse.keypairs.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/keypairs", path = {"userId"}, query = {"pageToken", "pageSize"} },
    ["gmail.users.settings.cse.keypairs.obliterate"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate", path = {"keyPairId", "userId"} },
    ["gmail.users.settings.delegates.create"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/delegates", path = {"userId"}, body = {"delegateEmail", "verificationStatus"} },
    ["gmail.users.settings.delegates.delete"] = { method = "DELETE", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/delegates/{delegateEmail}", path = {"userId", "delegateEmail"} },
    ["gmail.users.settings.delegates.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/delegates/{delegateEmail}", path = {"delegateEmail", "userId"} },
    ["gmail.users.settings.delegates.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/delegates", path = {"userId"} },
    ["gmail.users.settings.filters.create"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/filters", path = {"userId"}, body = {"action", "criteria", "id"} },
    ["gmail.users.settings.filters.delete"] = { method = "DELETE", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/filters/{id}", path = {"userId", "id"} },
    ["gmail.users.settings.filters.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/filters/{id}", path = {"id", "userId"} },
    ["gmail.users.settings.filters.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/filters", path = {"userId"} },
    ["gmail.users.settings.forwardingAddresses.create"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/forwardingAddresses", path = {"userId"}, body = {"forwardingEmail", "verificationStatus"} },
    ["gmail.users.settings.forwardingAddresses.delete"] = { method = "DELETE", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}", path = {"forwardingEmail", "userId"} },
    ["gmail.users.settings.forwardingAddresses.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}", path = {"forwardingEmail", "userId"} },
    ["gmail.users.settings.forwardingAddresses.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/forwardingAddresses", path = {"userId"} },
    ["gmail.users.settings.getAutoForwarding"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/autoForwarding", path = {"userId"} },
    ["gmail.users.settings.getImap"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/imap", path = {"userId"} },
    ["gmail.users.settings.getLanguage"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/language", path = {"userId"} },
    ["gmail.users.settings.getPop"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/pop", path = {"userId"} },
    ["gmail.users.settings.getVacation"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/vacation", path = {"userId"} },
    ["gmail.users.settings.sendAs.create"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs", path = {"userId"}, body = {"replyToAddress", "sendAsEmail", "treatAsAlias", "isDefault", "displayName", "verificationStatus", "smtpMsa", "signature", "isPrimary"} },
    ["gmail.users.settings.sendAs.delete"] = { method = "DELETE", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}", path = {"sendAsEmail", "userId"} },
    ["gmail.users.settings.sendAs.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}", path = {"userId", "sendAsEmail"} },
    ["gmail.users.settings.sendAs.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs", path = {"userId"} },
    ["gmail.users.settings.sendAs.patch"] = { method = "PATCH", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}", path = {"userId", "sendAsEmail"}, body = {"replyToAddress", "sendAsEmail", "treatAsAlias", "isDefault", "displayName", "verificationStatus", "smtpMsa", "signature", "isPrimary"} },
    ["gmail.users.settings.sendAs.smimeInfo.delete"] = { method = "DELETE", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}", path = {"id", "userId", "sendAsEmail"} },
    ["gmail.users.settings.sendAs.smimeInfo.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}", path = {"userId", "sendAsEmail", "id"} },
    ["gmail.users.settings.sendAs.smimeInfo.insert"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo", path = {"userId", "sendAsEmail"}, body = {"encryptedKeyPassword", "pem", "id", "issuerCn", "pkcs12", "expiration", "isDefault"} },
    ["gmail.users.settings.sendAs.smimeInfo.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo", path = {"sendAsEmail", "userId"} },
    ["gmail.users.settings.sendAs.smimeInfo.setDefault"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault", path = {"id", "userId", "sendAsEmail"} },
    ["gmail.users.settings.sendAs.update"] = { method = "PUT", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}", path = {"sendAsEmail", "userId"}, body = {"replyToAddress", "sendAsEmail", "treatAsAlias", "isDefault", "displayName", "verificationStatus", "smtpMsa", "signature", "isPrimary"} },
    ["gmail.users.settings.sendAs.verify"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify", path = {"sendAsEmail", "userId"} },
    ["gmail.users.settings.updateAutoForwarding"] = { method = "PUT", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/autoForwarding", path = {"userId"}, body = {"disposition", "emailAddress", "enabled"} },
    ["gmail.users.settings.updateImap"] = { method = "PUT", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/imap", path = {"userId"}, body = {"expungeBehavior", "maxFolderSize", "enabled", "autoExpunge"} },
    ["gmail.users.settings.updateLanguage"] = { method = "PUT", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/language", path = {"userId"}, body = {"displayLanguage"} },
    ["gmail.users.settings.updatePop"] = { method = "PUT", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/pop", path = {"userId"}, body = {"disposition", "accessWindow"} },
    ["gmail.users.settings.updateVacation"] = { method = "PUT", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/vacation", path = {"userId"}, body = {"restrictToContacts", "responseBodyHtml", "restrictToDomain", "responseBodyPlainText", "responseSubject", "startTime", "enableAutoReply", "endTime"} },
    ["gmail.users.stop"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/stop", path = {"userId"} },
    ["gmail.users.threads.delete"] = { method = "DELETE", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads/{id}", path = {"userId", "id"} },
    ["gmail.users.threads.get"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads/{id}", path = {"id", "userId"}, query = {"format", "metadataHeaders"} },
    ["gmail.users.threads.list"] = { method = "GET", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads", path = {"userId"}, query = {"includeSpamTrash", "maxResults", "pageToken", "labelIds", "q"} },
    ["gmail.users.threads.modify"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads/{id}/modify", path = {"id", "userId"}, body = {"removeLabelIds", "addLabelIds"} },
    ["gmail.users.threads.trash"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads/{id}/trash", path = {"userId", "id"} },
    ["gmail.users.threads.untrash"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads/{id}/untrash", path = {"userId", "id"} },
    ["gmail.users.watch"] = { method = "POST", url = "https://gmail.googleapis.com/gmail/v1/users/{userId}/watch", path = {"userId"}, body = {"labelIds", "labelFilterAction", "labelFilterBehavior", "topicName"} },
  },
}
