-- ScrollStash — every call this API accepts, as data.
--
-- GENERATED from https://api.scrollstash.com/v1/openapi.json
-- Published on the vendor's own documentation site (https://api.scrollstash.com).
-- 92 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "scrollstash-mcp",
  name = "ScrollStash",
  base = "https://mcp.scrollstash.com",
  docs = "https://nango.dev/docs/api-integrations/scrollstash-mcp",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "SCROLLSTASH_MCP_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["scrollstash-mcp.ads_by_brand"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/ads", path = {"brandId"}, query = {"limit", "cursor", "status", "format", "body_chars"} },
    ["scrollstash-mcp.ads_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/ads/{adId}", path = {"adId"} },
    ["scrollstash-mcp.ads_search"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/ads", query = {"limit", "cursor", "q", "brand_id", "format", "status", "country", "started_after"} },
    ["scrollstash-mcp.alerts_create"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts", path = {"ws"}, body = {"name", "event_type", "brand_ids", "cadence", "enabled", "email", "webhook_url", "webhook_kind"} },
    ["scrollstash-mcp.alerts_delete"] = { method = "DELETE", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts/{alertId}", path = {"ws", "alertId"} },
    ["scrollstash-mcp.alerts_deliveries"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alert-deliveries", path = {"ws"}, query = {"alert_id", "limit", "cursor"} },
    ["scrollstash-mcp.alerts_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.alerts_rotate_webhook_secret"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts/webhook-secret", path = {"ws"} },
    ["scrollstash-mcp.alerts_test"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts/{alertId}/test", path = {"ws", "alertId"} },
    ["scrollstash-mcp.alerts_update"] = { method = "PATCH", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts/{alertId}", path = {"ws", "alertId"}, body = {"name", "event_type", "brand_ids", "cadence", "enabled", "email", "webhook_url", "webhook_kind"} },
    ["scrollstash-mcp.api_keys_create"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/api-keys", path = {"ws"}, body = {"name", "scopes"} },
    ["scrollstash-mcp.api_keys_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/api-keys", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.api_keys_revoke"] = { method = "DELETE", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/api-keys/{keyId}", path = {"ws", "keyId"} },
    ["scrollstash-mcp.api_keys_revoke_unused"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/api-keys/revoke-unused", path = {"ws"}, body = {"unused_days"} },
    ["scrollstash-mcp.api_keys_rotate"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/api-keys/{keyId}/rotate", path = {"ws", "keyId"} },
    ["scrollstash-mcp.audience_segments"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/audience/{segment}", path = {"segment"}, query = {"limit", "cursor", "category_id"} },
    ["scrollstash-mcp.brands_breakdown"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/breakdown", path = {"brandId"} },
    ["scrollstash-mcp.brands_copy_reuse"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/copy-reuse", path = {"brandId"} },
    ["scrollstash-mcp.brands_creative_libraries"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brand-creative-library", query = {"brands", "sample"} },
    ["scrollstash-mcp.brands_creative_library"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/creative-library", path = {"brandId"}, query = {"sample"} },
    ["scrollstash-mcp.brands_daily_activities"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brand-daily-activity", query = {"brands", "days"} },
    ["scrollstash-mcp.brands_daily_activity"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/daily-activity", path = {"brandId"}, query = {"days"} },
    ["scrollstash-mcp.brands_demographics"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/demographics", path = {"brandId"} },
    ["scrollstash-mcp.brands_facebook_pages"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/facebook-pages", path = {"brandId"} },
    ["scrollstash-mcp.brands_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}", path = {"brandId"} },
    ["scrollstash-mcp.brands_leakage"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/leakage", path = {"brandId"} },
    ["scrollstash-mcp.brands_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands", query = {"limit", "cursor", "category_id", "country", "q", "letter", "sort"} },
    ["scrollstash-mcp.brands_network"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brand-network", query = {"brand_id", "category_id", "min_confidence"} },
    ["scrollstash-mcp.brands_partnerships"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/partnerships", path = {"brandId"} },
    ["scrollstash-mcp.brands_shop"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/shop", path = {"brandId"}, query = {"max_products"} },
    ["scrollstash-mcp.brands_similar"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/similar", path = {"brandId"}, query = {"limit"} },
    ["scrollstash-mcp.brands_sitemap"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/sitemap", query = {"limit", "cursor", "category_id", "similar_min"} },
    ["scrollstash-mcp.brands_split_tests"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/split-tests", path = {"brandId"} },
    ["scrollstash-mcp.brands_store"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/store", path = {"brandId"}, query = {"max_products"} },
    ["scrollstash-mcp.brands_tech_stack"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/tech-stack", path = {"brandId"} },
    ["scrollstash-mcp.brands_thumbs"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brand-thumbs", query = {"brands"} },
    ["scrollstash-mcp.brands_tiktok_shop"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/tiktok-shop", path = {"brandId"}, query = {"days", "max_products"} },
    ["scrollstash-mcp.brands_track"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/tracked-brands", path = {"ws"}, body = {"brand_id", "cadence"} },
    ["scrollstash-mcp.brands_tracked"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/tracked-brands", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.brands_tracked_freshness"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/tracked-brands/freshness", path = {"ws"} },
    ["scrollstash-mcp.brands_trajectory"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/trajectory", path = {"brandId"} },
    ["scrollstash-mcp.brands_untrack"] = { method = "DELETE", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/tracked-brands/{brandId}", path = {"ws", "brandId"} },
    ["scrollstash-mcp.brands_velocities"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brand-velocity", query = {"brands", "weeks"} },
    ["scrollstash-mcp.brands_velocity"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/velocity", path = {"brandId"}, query = {"weeks"} },
    ["scrollstash-mcp.briefs_feedback"] = { method = "PATCH", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/briefs/{briefId}", path = {"ws", "briefId"}, body = {"feedback"} },
    ["scrollstash-mcp.briefs_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/briefs/{briefId}", path = {"ws", "briefId"} },
    ["scrollstash-mcp.briefs_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/briefs", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.categories_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/categories/{categoryId}", path = {"categoryId"} },
    ["scrollstash-mcp.categories_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/categories", query = {"limit", "cursor", "parent_id", "slug"} },
    ["scrollstash-mcp.categories_sitemap"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/categories/sitemap", query = {"limit", "cursor"} },
    ["scrollstash-mcp.categories_stats"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/categories/{categoryId}/stats", path = {"categoryId"} },
    ["scrollstash-mcp.collections_add_item"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/collections/{collectionId}/items", path = {"ws", "collectionId"}, body = {"item_type", "item_key", "snapshot"} },
    ["scrollstash-mcp.collections_create"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/collections", path = {"ws"}, body = {"name", "description", "parent_id", "visibility", "first_item"} },
    ["scrollstash-mcp.collections_delete"] = { method = "DELETE", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/collections/{collectionId}", path = {"ws", "collectionId"} },
    ["scrollstash-mcp.collections_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/collections", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.collections_remove_item"] = { method = "DELETE", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/collections/{collectionId}/items/{itemType}/{itemKey}", path = {"ws", "collectionId", "itemType", "itemKey"} },
    ["scrollstash-mcp.collections_save"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/saved", path = {"ws"}, body = {"item_type", "item_key", "snapshot"} },
    ["scrollstash-mcp.collections_saved"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/saved", path = {"ws"}, query = {"item_type", "limit", "cursor"} },
    ["scrollstash-mcp.collections_unsave"] = { method = "DELETE", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/saved/{itemType}/{itemKey}", path = {"ws", "itemType", "itemKey"} },
    ["scrollstash-mcp.collections_update"] = { method = "PATCH", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/collections/{collectionId}", path = {"ws", "collectionId"}, body = {"name", "description", "parent_id", "visibility", "editor_ids"} },
    ["scrollstash-mcp.creatives_coverage"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/creative-coverage", query = {"brand_id"} },
    ["scrollstash-mcp.creatives_coverages"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brand-creative-coverage", query = {"brands"} },
    ["scrollstash-mcp.creatives_for_ad"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/ads/{adId}/creatives", path = {"adId"} },
    ["scrollstash-mcp.creatives_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/creatives/{creativeId}", path = {"creativeId"} },
    ["scrollstash-mcp.creatives_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/creatives", query = {"limit", "cursor", "ad_id", "brand_id"} },
    ["scrollstash-mcp.creatives_record"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/creative-records/{creativeKey}", path = {"creativeKey"} },
    ["scrollstash-mcp.creatives_records"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/creative-records/batch", query = {"keys"} },
    ["scrollstash-mcp.creatives_search"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/creative-records", query = {"limit", "cursor", "brand_id", "depth", "kind", "audience_gender", "audience_life_stage", "desire", "awareness", "hook_trigger", "lead_type", "narrative_form", "emotional_driver", "format", "production", "offer_type", "stage", "said", "on_screen", "q", "brand_said_s_min", "brand_said_s_max", "product_shown_s_min", "product_shown_s_max", "length_s_min", "length_s_max", "running_days_min", "running_days_max", "ads_min", "ads_max", "confidence_min", "confidence_max", "sort"} },
    ["scrollstash-mcp.me_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/me" },
    ["scrollstash-mcp.notes_delete"] = { method = "DELETE", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/notes/{noteId}", path = {"ws", "noteId"} },
    ["scrollstash-mcp.notes_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/notes", path = {"ws"}, query = {"subject_type", "subject_id", "limit", "cursor"} },
    ["scrollstash-mcp.notes_put"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/notes", path = {"ws"}, body = {"subject_type", "subject_id", "body"} },
    ["scrollstash-mcp.operators_family"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/operators", path = {"brandId"} },
    ["scrollstash-mcp.operators_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/operators/{operatorId}", path = {"operatorId"} },
    ["scrollstash-mcp.operators_hubs"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/hubs", query = {"limit", "cursor"} },
    ["scrollstash-mcp.operators_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/operators", query = {"limit", "cursor", "q"} },
    ["scrollstash-mcp.pages_details"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/page-details", query = {"ids"} },
    ["scrollstash-mcp.pages_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/pages/{pageId}", path = {"pageId"} },
    ["scrollstash-mcp.pages_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/pages", query = {"limit", "cursor", "brand_id", "page_type", "category_id", "q", "sort"} },
    ["scrollstash-mcp.radar_feed"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/radar", path = {"ws"}, query = {"days", "limit", "cursor"} },
    ["scrollstash-mcp.radar_signals"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/radar/signals", path = {"ws"}, query = {"days", "limit", "cursor"} },
    ["scrollstash-mcp.rankings_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/rankings", query = {"limit", "cursor", "category_id", "country", "sort"} },
    ["scrollstash-mcp.rankings_new_advertisers"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/rankings/new-advertisers", query = {"limit", "cursor", "category_id", "days"} },
    ["scrollstash-mcp.rankings_risers"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/rankings/risers", query = {"limit", "cursor", "category_id"} },
    ["scrollstash-mcp.reports_create"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/reports", path = {"ws"}, body = {"kind", "title", "brand_ids", "from", "to", "idempotency_key"} },
    ["scrollstash-mcp.reports_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/reports/{reportId}", path = {"ws", "reportId"} },
    ["scrollstash-mcp.reports_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/reports", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.system_freshness"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/system/freshness" },
    ["scrollstash-mcp.tools_brands"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/tools/{toolSlug}/brands", path = {"toolSlug"}, query = {"limit", "cursor", "category_id", "country"} },
    ["scrollstash-mcp.tools_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/tools/{toolSlug}", path = {"toolSlug"} },
    ["scrollstash-mcp.tools_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/tools", query = {"limit", "cursor"} },
    ["scrollstash-mcp.tools_testing_census"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/split-test-census" },
  },
}
