-- Streak — every call this API accepts, as data.
--
-- GENERATED from https://api.streak.com/api/openapi.json
-- Published on the vendor's own documentation site (https://api.streak.com).
-- 67 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "streak",
  name = "Streak",
  base = "https://api.streak.com/api",
  docs = "https://nango.dev/docs/api-integrations/streak",
  auth = {
    kind = "basic",
    header = "authorization",
    format = "Bearer {token}",
    env = nil,
    user_env = "STREAK_USER",
    pass_env = "STREAK_PASS",
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["streak.batch_get_boxes"] = { method = "POST", url = "https://api.streak.com/api/v1/pipelines/{pipelineKey}/boxes/batch", path = {"pipelineKey"} },
    ["streak.create_api_key"] = { method = "PUT", url = "https://api.streak.com/api/v1/apikeys", query = {"teamKey"} },
    ["streak.create_comment"] = { method = "POST", url = "https://api.streak.com/api/v2/boxes/{boxKey}/comments", path = {"boxKey"}, body = {"message", "mentions", "parent", "searchForAtMentions"} },
    ["streak.create_contact"] = { method = "POST", url = "https://api.streak.com/api/v2/teams/{teamKey}/contacts", path = {"teamKey"}, query = {"getIfExisting"}, body = {"givenName", "familyName", "title", "other", "emailAddresses", "phoneNumbers", "addresses", "domains", "twitterHandle", "facebookHandle", "linkedinHandle", "instagramHandle", "photoUrl"} },
    ["streak.create_field"] = { method = "POST", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/fields", path = {"pipelineKey"}, body = {"name", "type", "defaultValue"} },
    ["streak.create_meeting"] = { method = "POST", url = "https://api.streak.com/api/v2/boxes/{boxKey}/meetings", path = {"boxKey"}, body = {"meetingType", "startTimestamp", "duration", "notes", "taskKeys", "isDraft"} },
    ["streak.create_organization"] = { method = "POST", url = "https://api.streak.com/api/v2/teams/{teamKey}/organizations", path = {"teamKey"}, query = {"getIfExisting"}, body = {"name", "other", "domains", "industry", "phoneNumbers", "addresses", "employeeCount", "logoURL", "twitterHandle", "facebookHandle", "linkedinHandle", "instagramHandle"} },
    ["streak.create_pipeline"] = { method = "POST", url = "https://api.streak.com/api/v2/pipelines", body = {"name", "teamKey", "stages", "icon", "description", "templateType", "fields", "defaultPermissionSetName", "sharingRestrictedToTeam"} },
    ["streak.create_stage"] = { method = "POST", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/stages", path = {"pipelineKey"}, body = {"name", "color"} },
    ["streak.create_task"] = { method = "POST", url = "https://api.streak.com/api/v2/boxes/{boxKey}/tasks", path = {"boxKey"}, body = {"text", "dueDate", "assignedTo", "meetingKey", "isDraft", "teamContactKey", "draft"} },
    ["streak.create_team"] = { method = "POST", url = "https://api.streak.com/api/v2/teams", body = {"name", "members"} },
    ["streak.delete_api_key"] = { method = "DELETE", url = "https://api.streak.com/api/v1/apikeys/{apiKeyKey}", path = {"apiKeyKey"} },
    ["streak.delete_comment"] = { method = "DELETE", url = "https://api.streak.com/api/v2/comments/{commentKey}", path = {"commentKey"} },
    ["streak.delete_contact"] = { method = "DELETE", url = "https://api.streak.com/api/v2/contacts/{contactKey}", path = {"contactKey"} },
    ["streak.delete_field"] = { method = "DELETE", url = "https://api.streak.com/api/v1/pipelines/{pipelineKey}/fields/{fieldKey}", path = {"fieldKey", "pipelineKey"} },
    ["streak.delete_meeting"] = { method = "DELETE", url = "https://api.streak.com/api/v2/meetings/{meetingKey}", path = {"meetingKey"} },
    ["streak.delete_organization"] = { method = "DELETE", url = "https://api.streak.com/api/v2/organizations/{organizationKey}", path = {"organizationKey"} },
    ["streak.delete_pipeline"] = { method = "DELETE", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}", path = {"pipelineKey"} },
    ["streak.delete_stage"] = { method = "DELETE", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/stages/{stageKey}", path = {"pipelineKey", "stageKey"} },
    ["streak.delete_task"] = { method = "DELETE", url = "https://api.streak.com/api/v2/tasks/{taskKey}", path = {"taskKey"} },
    ["streak.get_api_keys"] = { method = "GET", url = "https://api.streak.com/api/v1/apikeys", query = {"limit", "page"} },
    ["streak.get_assigned_tasks"] = { method = "GET", url = "https://api.streak.com/api/v2/tasks", query = {"direction", "includeCompleted", "limit", "pipelineKey", "sortOrder", "userKeys"} },
    ["streak.get_box"] = { method = "GET", url = "https://api.streak.com/api/v1/boxes/{boxKey}", path = {"boxKey"} },
    ["streak.get_box_markdown"] = { method = "GET", url = "https://api.streak.com/api/v1/boxes/{boxKey}/md", path = {"boxKey"}, query = {"maxTokens"} },
    ["streak.get_comment"] = { method = "GET", url = "https://api.streak.com/api/v2/comments/{commentKey}", path = {"commentKey"} },
    ["streak.get_comments"] = { method = "GET", url = "https://api.streak.com/api/v2/boxes/{boxKey}/comments", path = {"boxKey"} },
    ["streak.get_contact"] = { method = "GET", url = "https://api.streak.com/api/v2/contacts/{contactKey}", path = {"contactKey"} },
    ["streak.get_contacts"] = { method = "POST", url = "https://api.streak.com/api/v2/contacts/batch/get" },
    ["streak.get_current_user"] = { method = "GET", url = "https://api.streak.com/api/v1/users/me" },
    ["streak.get_current_user_teams"] = { method = "GET", url = "https://api.streak.com/api/v2/users/me/teams", query = {"limit", "page"} },
    ["streak.get_field"] = { method = "GET", url = "https://api.streak.com/api/v1/pipelines/{pipelineKey}/fields/{fieldKey}", path = {"fieldKey", "pipelineKey"} },
    ["streak.get_meeting"] = { method = "GET", url = "https://api.streak.com/api/v2/meetings/{meetingKey}", path = {"meetingKey"} },
    ["streak.get_meetings"] = { method = "GET", url = "https://api.streak.com/api/v2/boxes/{boxKey}/meetings", path = {"boxKey"}, query = {"limit", "page"} },
    ["streak.get_organization"] = { method = "GET", url = "https://api.streak.com/api/v2/organizations/{organizationKey}", path = {"organizationKey"} },
    ["streak.get_organizations"] = { method = "POST", url = "https://api.streak.com/api/v2/organizations/batch/get" },
    ["streak.get_pipeline"] = { method = "GET", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}", path = {"pipelineKey"} },
    ["streak.get_recent_boxes"] = { method = "GET", url = "https://api.streak.com/api/v2/boxes/recent", query = {"limit"} },
    ["streak.get_stage"] = { method = "GET", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/stages/{stageKey}", path = {"pipelineKey", "stageKey"} },
    ["streak.get_task"] = { method = "GET", url = "https://api.streak.com/api/v2/tasks/{taskKey}", path = {"taskKey"} },
    ["streak.get_tasks_for_box"] = { method = "GET", url = "https://api.streak.com/api/v2/boxes/{boxKey}/tasks", path = {"boxKey"}, query = {"limit", "page"} },
    ["streak.get_team"] = { method = "GET", url = "https://api.streak.com/api/v2/teams/{teamKey}", path = {"teamKey"} },
    ["streak.get_trending_boxes"] = { method = "GET", url = "https://api.streak.com/api/v2/boxes/trending", query = {"limit"} },
    ["streak.get_user"] = { method = "GET", url = "https://api.streak.com/api/v1/users/{userKey}", path = {"userKey"} },
    ["streak.get_user_settings"] = { method = "GET", url = "https://api.streak.com/api/v2/users/me/settings" },
    ["streak.get_users_on_team"] = { method = "GET", url = "https://api.streak.com/api/v2/teams/{teamKey}/users", path = {"teamKey"} },
    ["streak.list_boxes"] = { method = "GET", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/boxes", path = {"pipelineKey"}, query = {"assignedToKey", "sortBy", "stageKey", "limit", "page"} },
    ["streak.list_contact_boxes"] = { method = "GET", url = "https://api.streak.com/api/v2/contacts/{contactKey}/boxes", path = {"contactKey"}, query = {"cursor"} },
    ["streak.list_contacts"] = { method = "GET", url = "https://api.streak.com/api/v2/teams/{teamKey}/contacts", path = {"teamKey"}, query = {"after", "cursor", "limit"} },
    ["streak.list_fields"] = { method = "GET", url = "https://api.streak.com/api/v1/pipelines/{pipelineKey}/fields", path = {"pipelineKey"} },
    ["streak.list_organization_boxes"] = { method = "GET", url = "https://api.streak.com/api/v2/organizations/{organizationKey}/boxes", path = {"organizationKey"}, query = {"cursor"} },
    ["streak.list_organizations"] = { method = "GET", url = "https://api.streak.com/api/v2/teams/{teamKey}/organizations", path = {"teamKey"}, query = {"cursor", "limit"} },
    ["streak.list_pipelines"] = { method = "GET", url = "https://api.streak.com/api/v2/pipelines", query = {"sortBy", "limit", "page"} },
    ["streak.list_stages"] = { method = "GET", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/stages", path = {"pipelineKey"} },
    ["streak.react_to_comment"] = { method = "POST", url = "https://api.streak.com/api/v2/comments/{commentKey}/react", path = {"commentKey"}, body = {"emoji"} },
    ["streak.search"] = { method = "GET", url = "https://api.streak.com/api/v1/search", query = {"name", "page", "pipelineKey", "query", "stageKey", "teamKey"} },
    ["streak.unreact_to_comment"] = { method = "POST", url = "https://api.streak.com/api/v2/comments/{commentKey}/unreact", path = {"commentKey"}, body = {"emoji"} },
    ["streak.update_comment"] = { method = "POST", url = "https://api.streak.com/api/v2/comments/{commentKey}", path = {"commentKey"}, body = {"message", "mentions"} },
    ["streak.update_contact"] = { method = "POST", url = "https://api.streak.com/api/v2/contacts/{contactKey}", path = {"contactKey"}, body = {"givenName", "familyName", "title", "other", "emailAddresses", "phoneNumbers", "addresses", "domains", "twitterHandle", "facebookHandle", "linkedinHandle", "instagramHandle", "photoUrl", "fields", "contactLinks", "orgLinks"} },
    ["streak.update_field"] = { method = "POST", url = "https://api.streak.com/api/v1/pipelines/{pipelineKey}/fields/{fieldKey}", path = {"fieldKey", "pipelineKey"}, query = {"addOnly"}, body = {"name", "defaultValue", "dropdownSettings", "tagSettings", "aiSettings"} },
    ["streak.update_meeting"] = { method = "POST", url = "https://api.streak.com/api/v2/meetings/{meetingKey}", path = {"meetingKey"}, body = {"meetingType", "startTimestamp", "duration", "notes", "isDraft", "taskKeys"} },
    ["streak.update_organization"] = { method = "POST", url = "https://api.streak.com/api/v2/organizations/{organizationKey}", path = {"organizationKey"}, body = {"name", "other", "domains", "industry", "phoneNumbers", "addresses", "employeeCount", "logoURL", "twitterHandle", "facebookHandle", "linkedinHandle", "instagramHandle", "contactLinks", "orgLinks", "fields"} },
    ["streak.update_pipeline"] = { method = "POST", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}", path = {"pipelineKey"}, body = {"teamKey", "icon", "name", "description", "sharingRestrictedToTeam", "stageOrder", "stageColorTheme", "customPermissionSets", "defaultPermissionSetName", "aclEntries"} },
    ["streak.update_stage"] = { method = "POST", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/stages/{stageKey}", path = {"pipelineKey", "stageKey"}, body = {"name", "color"} },
    ["streak.update_task"] = { method = "POST", url = "https://api.streak.com/api/v2/tasks/{taskKey}", path = {"taskKey"}, body = {"text", "dueDate", "status", "assignedTo", "meetingKey", "isDraft", "draft"} },
    ["streak.update_team"] = { method = "POST", url = "https://api.streak.com/api/v2/teams/{teamKey}", path = {"teamKey"}, body = {"name", "sharingRestrictedToTeam", "automaticallyApproveJoinRequests", "automaticallySendInvoiceEmails", "emailsToSendInvoiceTo", "members", "contactOrgListPermissions", "contactSettings", "organizationSettings"} },
    ["streak.update_user"] = { method = "POST", url = "https://api.streak.com/api/v1/users/{userKey}", path = {"userKey"}, body = {"timezoneId", "firstName", "lastName", "automaticallySendInvoiceEmails", "emailsToSendInvoiceTo", "customerSpecifiedInvoiceData"} },
    ["streak.update_user_settings"] = { method = "POST", url = "https://api.streak.com/api/v2/users/me/settings", body = {"streakIt", "listIndicatorType", "pixelTrackingDefaultOn", "snippetAutoComplete", "pipelineShared", "followedBox", "followedBoxStageChange", "followedBoxNewComment", "followedAssignedToMe", "followedAssignedToSelf", "followedBoxDataChange", "anyBox", "anyBoxStageChange", "anyBoxNewComment", "anyBoxDataChange", "newBox", "tasks", "tasksCompleted", "meetings", "importJobStatus", "firstTrackedThreadRead", "firstTrackedThreadClick"} },
  },
}
